// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckquestion"
)

// IntelCheckQuestionCreate is the builder for creating a IntelCheckQuestion entity.
type IntelCheckQuestionCreate struct {
	config
	mutation *IntelCheckQuestionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntelCheckQuestionCreate) SetCreatedAt(v time.Time) *IntelCheckQuestionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableCreatedAt(v *time.Time) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntelCheckQuestionCreate) SetUpdatedAt(v time.Time) *IntelCheckQuestionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableUpdatedAt(v *time.Time) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *IntelCheckQuestionCreate) SetKind(v intelcheckquestion.Kind) *IntelCheckQuestionCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *IntelCheckQuestionCreate) SetTitle(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *IntelCheckQuestionCreate) SetPrompt(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetExpectedAnswer sets the "expected_answer" field.
func (_c *IntelCheckQuestionCreate) SetExpectedAnswer(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetExpectedAnswer(v)
	return _c
}

// SetNillableExpectedAnswer sets the "expected_answer" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableExpectedAnswer(v *string) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetExpectedAnswer(*v)
	}
	return _c
}

// SetMatchMode sets the "match_mode" field.
func (_c *IntelCheckQuestionCreate) SetMatchMode(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetMatchMode(v)
	return _c
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableMatchMode(v *string) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetMatchMode(*v)
	}
	return _c
}

// SetReferenceHTML sets the "reference_html" field.
func (_c *IntelCheckQuestionCreate) SetReferenceHTML(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetReferenceHTML(v)
	return _c
}

// SetNillableReferenceHTML sets the "reference_html" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableReferenceHTML(v *string) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetReferenceHTML(*v)
	}
	return _c
}

// SetReferenceMetrics sets the "reference_metrics" field.
func (_c *IntelCheckQuestionCreate) SetReferenceMetrics(v map[string]interface{}) *IntelCheckQuestionCreate {
	_c.mutation.SetReferenceMetrics(v)
	return _c
}

// SetDrawingRules sets the "drawing_rules" field.
func (_c *IntelCheckQuestionCreate) SetDrawingRules(v map[string]interface{}) *IntelCheckQuestionCreate {
	_c.mutation.SetDrawingRules(v)
	return _c
}

// SetReviewRubric sets the "review_rubric" field.
func (_c *IntelCheckQuestionCreate) SetReviewRubric(v string) *IntelCheckQuestionCreate {
	_c.mutation.SetReviewRubric(v)
	return _c
}

// SetNillableReviewRubric sets the "review_rubric" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableReviewRubric(v *string) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetReviewRubric(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *IntelCheckQuestionCreate) SetEnabled(v bool) *IntelCheckQuestionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *IntelCheckQuestionCreate) SetNillableEnabled(v *bool) *IntelCheckQuestionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the IntelCheckQuestionMutation object of the builder.
func (_c *IntelCheckQuestionCreate) Mutation() *IntelCheckQuestionMutation {
	return _c.mutation
}

// Save creates the IntelCheckQuestion in the database.
func (_c *IntelCheckQuestionCreate) Save(ctx context.Context) (*IntelCheckQuestion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntelCheckQuestionCreate) SaveX(ctx context.Context) *IntelCheckQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelCheckQuestionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelCheckQuestionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntelCheckQuestionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := intelcheckquestion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := intelcheckquestion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ExpectedAnswer(); !ok {
		v := intelcheckquestion.DefaultExpectedAnswer
		_c.mutation.SetExpectedAnswer(v)
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		v := intelcheckquestion.DefaultMatchMode
		_c.mutation.SetMatchMode(v)
	}
	if _, ok := _c.mutation.ReferenceHTML(); !ok {
		v := intelcheckquestion.DefaultReferenceHTML
		_c.mutation.SetReferenceHTML(v)
	}
	if _, ok := _c.mutation.ReviewRubric(); !ok {
		v := intelcheckquestion.DefaultReviewRubric
		_c.mutation.SetReviewRubric(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := intelcheckquestion.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntelCheckQuestionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IntelCheckQuestion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IntelCheckQuestion.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "IntelCheckQuestion.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := intelcheckquestion.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "IntelCheckQuestion.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "IntelCheckQuestion.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := intelcheckquestion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "IntelCheckQuestion.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "IntelCheckQuestion.prompt"`)}
	}
	if v, ok := _c.mutation.Prompt(); ok {
		if err := intelcheckquestion.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "IntelCheckQuestion.prompt": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExpectedAnswer(); ok {
		if err := intelcheckquestion.ExpectedAnswerValidator(v); err != nil {
			return &ValidationError{Name: "expected_answer", err: fmt.Errorf(`ent: validator failed for field "IntelCheckQuestion.expected_answer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		return &ValidationError{Name: "match_mode", err: errors.New(`ent: missing required field "IntelCheckQuestion.match_mode"`)}
	}
	if v, ok := _c.mutation.MatchMode(); ok {
		if err := intelcheckquestion.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "IntelCheckQuestion.match_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "IntelCheckQuestion.enabled"`)}
	}
	return nil
}

func (_c *IntelCheckQuestionCreate) sqlSave(ctx context.Context) (*IntelCheckQuestion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntelCheckQuestionCreate) createSpec() (*IntelCheckQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &IntelCheckQuestion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(intelcheckquestion.Table, sqlgraph.NewFieldSpec(intelcheckquestion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(intelcheckquestion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(intelcheckquestion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(intelcheckquestion.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(intelcheckquestion.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(intelcheckquestion.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.ExpectedAnswer(); ok {
		_spec.SetField(intelcheckquestion.FieldExpectedAnswer, field.TypeString, value)
		_node.ExpectedAnswer = value
	}
	if value, ok := _c.mutation.MatchMode(); ok {
		_spec.SetField(intelcheckquestion.FieldMatchMode, field.TypeString, value)
		_node.MatchMode = value
	}
	if value, ok := _c.mutation.ReferenceHTML(); ok {
		_spec.SetField(intelcheckquestion.FieldReferenceHTML, field.TypeString, value)
		_node.ReferenceHTML = value
	}
	if value, ok := _c.mutation.ReferenceMetrics(); ok {
		_spec.SetField(intelcheckquestion.FieldReferenceMetrics, field.TypeJSON, value)
		_node.ReferenceMetrics = value
	}
	if value, ok := _c.mutation.DrawingRules(); ok {
		_spec.SetField(intelcheckquestion.FieldDrawingRules, field.TypeJSON, value)
		_node.DrawingRules = value
	}
	if value, ok := _c.mutation.ReviewRubric(); ok {
		_spec.SetField(intelcheckquestion.FieldReviewRubric, field.TypeString, value)
		_node.ReviewRubric = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(intelcheckquestion.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelCheckQuestion.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelCheckQuestionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelCheckQuestionCreate) OnConflict(opts ...sql.ConflictOption) *IntelCheckQuestionUpsertOne {
	_c.conflict = opts
	return &IntelCheckQuestionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelCheckQuestionCreate) OnConflictColumns(columns ...string) *IntelCheckQuestionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelCheckQuestionUpsertOne{
		create: _c,
	}
}

type (
	// IntelCheckQuestionUpsertOne is the builder for "upsert"-ing
	//  one IntelCheckQuestion node.
	IntelCheckQuestionUpsertOne struct {
		create *IntelCheckQuestionCreate
	}

	// IntelCheckQuestionUpsert is the "OnConflict" setter.
	IntelCheckQuestionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckQuestionUpsert) SetUpdatedAt(v time.Time) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateUpdatedAt() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldUpdatedAt)
	return u
}

// SetKind sets the "kind" field.
func (u *IntelCheckQuestionUpsert) SetKind(v intelcheckquestion.Kind) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateKind() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldKind)
	return u
}

// SetTitle sets the "title" field.
func (u *IntelCheckQuestionUpsert) SetTitle(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateTitle() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldTitle)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *IntelCheckQuestionUpsert) SetPrompt(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdatePrompt() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldPrompt)
	return u
}

// SetExpectedAnswer sets the "expected_answer" field.
func (u *IntelCheckQuestionUpsert) SetExpectedAnswer(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldExpectedAnswer, v)
	return u
}

// UpdateExpectedAnswer sets the "expected_answer" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateExpectedAnswer() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldExpectedAnswer)
	return u
}

// ClearExpectedAnswer clears the value of the "expected_answer" field.
func (u *IntelCheckQuestionUpsert) ClearExpectedAnswer() *IntelCheckQuestionUpsert {
	u.SetNull(intelcheckquestion.FieldExpectedAnswer)
	return u
}

// SetMatchMode sets the "match_mode" field.
func (u *IntelCheckQuestionUpsert) SetMatchMode(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldMatchMode, v)
	return u
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateMatchMode() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldMatchMode)
	return u
}

// SetReferenceHTML sets the "reference_html" field.
func (u *IntelCheckQuestionUpsert) SetReferenceHTML(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldReferenceHTML, v)
	return u
}

// UpdateReferenceHTML sets the "reference_html" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateReferenceHTML() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldReferenceHTML)
	return u
}

// ClearReferenceHTML clears the value of the "reference_html" field.
func (u *IntelCheckQuestionUpsert) ClearReferenceHTML() *IntelCheckQuestionUpsert {
	u.SetNull(intelcheckquestion.FieldReferenceHTML)
	return u
}

// SetReferenceMetrics sets the "reference_metrics" field.
func (u *IntelCheckQuestionUpsert) SetReferenceMetrics(v map[string]interface{}) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldReferenceMetrics, v)
	return u
}

// UpdateReferenceMetrics sets the "reference_metrics" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateReferenceMetrics() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldReferenceMetrics)
	return u
}

// ClearReferenceMetrics clears the value of the "reference_metrics" field.
func (u *IntelCheckQuestionUpsert) ClearReferenceMetrics() *IntelCheckQuestionUpsert {
	u.SetNull(intelcheckquestion.FieldReferenceMetrics)
	return u
}

// SetDrawingRules sets the "drawing_rules" field.
func (u *IntelCheckQuestionUpsert) SetDrawingRules(v map[string]interface{}) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldDrawingRules, v)
	return u
}

// UpdateDrawingRules sets the "drawing_rules" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateDrawingRules() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldDrawingRules)
	return u
}

// ClearDrawingRules clears the value of the "drawing_rules" field.
func (u *IntelCheckQuestionUpsert) ClearDrawingRules() *IntelCheckQuestionUpsert {
	u.SetNull(intelcheckquestion.FieldDrawingRules)
	return u
}

// SetReviewRubric sets the "review_rubric" field.
func (u *IntelCheckQuestionUpsert) SetReviewRubric(v string) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldReviewRubric, v)
	return u
}

// UpdateReviewRubric sets the "review_rubric" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateReviewRubric() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldReviewRubric)
	return u
}

// ClearReviewRubric clears the value of the "review_rubric" field.
func (u *IntelCheckQuestionUpsert) ClearReviewRubric() *IntelCheckQuestionUpsert {
	u.SetNull(intelcheckquestion.FieldReviewRubric)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckQuestionUpsert) SetEnabled(v bool) *IntelCheckQuestionUpsert {
	u.Set(intelcheckquestion.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsert) UpdateEnabled() *IntelCheckQuestionUpsert {
	u.SetExcluded(intelcheckquestion.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelCheckQuestionUpsertOne) UpdateNewValues() *IntelCheckQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(intelcheckquestion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntelCheckQuestionUpsertOne) Ignore() *IntelCheckQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelCheckQuestionUpsertOne) DoNothing() *IntelCheckQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelCheckQuestionCreate.OnConflict
// documentation for more info.
func (u *IntelCheckQuestionUpsertOne) Update(set func(*IntelCheckQuestionUpsert)) *IntelCheckQuestionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelCheckQuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckQuestionUpsertOne) SetUpdatedAt(v time.Time) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateUpdatedAt() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *IntelCheckQuestionUpsertOne) SetKind(v intelcheckquestion.Kind) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateKind() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateKind()
	})
}

// SetTitle sets the "title" field.
func (u *IntelCheckQuestionUpsertOne) SetTitle(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateTitle() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateTitle()
	})
}

// SetPrompt sets the "prompt" field.
func (u *IntelCheckQuestionUpsertOne) SetPrompt(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdatePrompt() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdatePrompt()
	})
}

// SetExpectedAnswer sets the "expected_answer" field.
func (u *IntelCheckQuestionUpsertOne) SetExpectedAnswer(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetExpectedAnswer(v)
	})
}

// UpdateExpectedAnswer sets the "expected_answer" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateExpectedAnswer() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateExpectedAnswer()
	})
}

// ClearExpectedAnswer clears the value of the "expected_answer" field.
func (u *IntelCheckQuestionUpsertOne) ClearExpectedAnswer() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearExpectedAnswer()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *IntelCheckQuestionUpsertOne) SetMatchMode(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateMatchMode() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateMatchMode()
	})
}

// SetReferenceHTML sets the "reference_html" field.
func (u *IntelCheckQuestionUpsertOne) SetReferenceHTML(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReferenceHTML(v)
	})
}

// UpdateReferenceHTML sets the "reference_html" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateReferenceHTML() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReferenceHTML()
	})
}

// ClearReferenceHTML clears the value of the "reference_html" field.
func (u *IntelCheckQuestionUpsertOne) ClearReferenceHTML() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReferenceHTML()
	})
}

// SetReferenceMetrics sets the "reference_metrics" field.
func (u *IntelCheckQuestionUpsertOne) SetReferenceMetrics(v map[string]interface{}) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReferenceMetrics(v)
	})
}

// UpdateReferenceMetrics sets the "reference_metrics" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateReferenceMetrics() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReferenceMetrics()
	})
}

// ClearReferenceMetrics clears the value of the "reference_metrics" field.
func (u *IntelCheckQuestionUpsertOne) ClearReferenceMetrics() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReferenceMetrics()
	})
}

// SetDrawingRules sets the "drawing_rules" field.
func (u *IntelCheckQuestionUpsertOne) SetDrawingRules(v map[string]interface{}) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetDrawingRules(v)
	})
}

// UpdateDrawingRules sets the "drawing_rules" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateDrawingRules() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateDrawingRules()
	})
}

// ClearDrawingRules clears the value of the "drawing_rules" field.
func (u *IntelCheckQuestionUpsertOne) ClearDrawingRules() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearDrawingRules()
	})
}

// SetReviewRubric sets the "review_rubric" field.
func (u *IntelCheckQuestionUpsertOne) SetReviewRubric(v string) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReviewRubric(v)
	})
}

// UpdateReviewRubric sets the "review_rubric" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateReviewRubric() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReviewRubric()
	})
}

// ClearReviewRubric clears the value of the "review_rubric" field.
func (u *IntelCheckQuestionUpsertOne) ClearReviewRubric() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReviewRubric()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckQuestionUpsertOne) SetEnabled(v bool) *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertOne) UpdateEnabled() *IntelCheckQuestionUpsertOne {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *IntelCheckQuestionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelCheckQuestionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelCheckQuestionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntelCheckQuestionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntelCheckQuestionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntelCheckQuestionCreateBulk is the builder for creating many IntelCheckQuestion entities in bulk.
type IntelCheckQuestionCreateBulk struct {
	config
	err      error
	builders []*IntelCheckQuestionCreate
	conflict []sql.ConflictOption
}

// Save creates the IntelCheckQuestion entities in the database.
func (_c *IntelCheckQuestionCreateBulk) Save(ctx context.Context) ([]*IntelCheckQuestion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntelCheckQuestion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntelCheckQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntelCheckQuestionCreateBulk) SaveX(ctx context.Context) []*IntelCheckQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelCheckQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelCheckQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelCheckQuestion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelCheckQuestionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelCheckQuestionCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntelCheckQuestionUpsertBulk {
	_c.conflict = opts
	return &IntelCheckQuestionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelCheckQuestionCreateBulk) OnConflictColumns(columns ...string) *IntelCheckQuestionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelCheckQuestionUpsertBulk{
		create: _c,
	}
}

// IntelCheckQuestionUpsertBulk is the builder for "upsert"-ing
// a bulk of IntelCheckQuestion nodes.
type IntelCheckQuestionUpsertBulk struct {
	create *IntelCheckQuestionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelCheckQuestionUpsertBulk) UpdateNewValues() *IntelCheckQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(intelcheckquestion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelCheckQuestion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntelCheckQuestionUpsertBulk) Ignore() *IntelCheckQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelCheckQuestionUpsertBulk) DoNothing() *IntelCheckQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelCheckQuestionCreateBulk.OnConflict
// documentation for more info.
func (u *IntelCheckQuestionUpsertBulk) Update(set func(*IntelCheckQuestionUpsert)) *IntelCheckQuestionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelCheckQuestionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckQuestionUpsertBulk) SetUpdatedAt(v time.Time) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateUpdatedAt() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetKind sets the "kind" field.
func (u *IntelCheckQuestionUpsertBulk) SetKind(v intelcheckquestion.Kind) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateKind() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateKind()
	})
}

// SetTitle sets the "title" field.
func (u *IntelCheckQuestionUpsertBulk) SetTitle(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateTitle() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateTitle()
	})
}

// SetPrompt sets the "prompt" field.
func (u *IntelCheckQuestionUpsertBulk) SetPrompt(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdatePrompt() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdatePrompt()
	})
}

// SetExpectedAnswer sets the "expected_answer" field.
func (u *IntelCheckQuestionUpsertBulk) SetExpectedAnswer(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetExpectedAnswer(v)
	})
}

// UpdateExpectedAnswer sets the "expected_answer" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateExpectedAnswer() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateExpectedAnswer()
	})
}

// ClearExpectedAnswer clears the value of the "expected_answer" field.
func (u *IntelCheckQuestionUpsertBulk) ClearExpectedAnswer() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearExpectedAnswer()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *IntelCheckQuestionUpsertBulk) SetMatchMode(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateMatchMode() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateMatchMode()
	})
}

// SetReferenceHTML sets the "reference_html" field.
func (u *IntelCheckQuestionUpsertBulk) SetReferenceHTML(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReferenceHTML(v)
	})
}

// UpdateReferenceHTML sets the "reference_html" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateReferenceHTML() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReferenceHTML()
	})
}

// ClearReferenceHTML clears the value of the "reference_html" field.
func (u *IntelCheckQuestionUpsertBulk) ClearReferenceHTML() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReferenceHTML()
	})
}

// SetReferenceMetrics sets the "reference_metrics" field.
func (u *IntelCheckQuestionUpsertBulk) SetReferenceMetrics(v map[string]interface{}) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReferenceMetrics(v)
	})
}

// UpdateReferenceMetrics sets the "reference_metrics" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateReferenceMetrics() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReferenceMetrics()
	})
}

// ClearReferenceMetrics clears the value of the "reference_metrics" field.
func (u *IntelCheckQuestionUpsertBulk) ClearReferenceMetrics() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReferenceMetrics()
	})
}

// SetDrawingRules sets the "drawing_rules" field.
func (u *IntelCheckQuestionUpsertBulk) SetDrawingRules(v map[string]interface{}) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetDrawingRules(v)
	})
}

// UpdateDrawingRules sets the "drawing_rules" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateDrawingRules() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateDrawingRules()
	})
}

// ClearDrawingRules clears the value of the "drawing_rules" field.
func (u *IntelCheckQuestionUpsertBulk) ClearDrawingRules() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearDrawingRules()
	})
}

// SetReviewRubric sets the "review_rubric" field.
func (u *IntelCheckQuestionUpsertBulk) SetReviewRubric(v string) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetReviewRubric(v)
	})
}

// UpdateReviewRubric sets the "review_rubric" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateReviewRubric() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateReviewRubric()
	})
}

// ClearReviewRubric clears the value of the "review_rubric" field.
func (u *IntelCheckQuestionUpsertBulk) ClearReviewRubric() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.ClearReviewRubric()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckQuestionUpsertBulk) SetEnabled(v bool) *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckQuestionUpsertBulk) UpdateEnabled() *IntelCheckQuestionUpsertBulk {
	return u.Update(func(s *IntelCheckQuestionUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *IntelCheckQuestionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntelCheckQuestionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelCheckQuestionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelCheckQuestionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
