// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckresult"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckround"
	"github.com/Wei-Shaw/sub2api/ent/intelchecktarget"
)

// IntelCheckResult is the model entity for the IntelCheckResult schema.
type IntelCheckResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RoundID holds the value of the "round_id" field.
	RoundID int64 `json:"round_id,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID int64 `json:"target_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind intelcheckresult.Kind `json:"kind,omitempty"`
	// Status holds the value of the "status" field.
	Status intelcheckresult.Status `json:"status,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs *int `json:"latency_ms,omitempty"`
	// PromptSnapshot holds the value of the "prompt_snapshot" field.
	PromptSnapshot string `json:"prompt_snapshot,omitempty"`
	// RawReply holds the value of the "raw_reply" field.
	RawReply string `json:"raw_reply,omitempty"`
	// ExtractedAnswer holds the value of the "extracted_answer" field.
	ExtractedAnswer string `json:"extracted_answer,omitempty"`
	// HTMLOutput holds the value of the "html_output" field.
	HTMLOutput string `json:"html_output,omitempty"`
	// JudgeDetail holds the value of the "judge_detail" field.
	JudgeDetail map[string]interface{} `json:"judge_detail,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens *int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens *int `json:"output_tokens,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IntelCheckResultQuery when eager-loading is set.
	Edges        IntelCheckResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IntelCheckResultEdges holds the relations/edges for other nodes in the graph.
type IntelCheckResultEdges struct {
	// Round holds the value of the round edge.
	Round *IntelCheckRound `json:"round,omitempty"`
	// Target holds the value of the target edge.
	Target *IntelCheckTarget `json:"target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoundOrErr returns the Round value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IntelCheckResultEdges) RoundOrErr() (*IntelCheckRound, error) {
	if e.Round != nil {
		return e.Round, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: intelcheckround.Label}
	}
	return nil, &NotLoadedError{edge: "round"}
}

// TargetOrErr returns the Target value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IntelCheckResultEdges) TargetOrErr() (*IntelCheckTarget, error) {
	if e.Target != nil {
		return e.Target, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: intelchecktarget.Label}
	}
	return nil, &NotLoadedError{edge: "target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntelCheckResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intelcheckresult.FieldJudgeDetail:
			values[i] = new([]byte)
		case intelcheckresult.FieldID, intelcheckresult.FieldRoundID, intelcheckresult.FieldTargetID, intelcheckresult.FieldLatencyMs, intelcheckresult.FieldInputTokens, intelcheckresult.FieldOutputTokens:
			values[i] = new(sql.NullInt64)
		case intelcheckresult.FieldKind, intelcheckresult.FieldStatus, intelcheckresult.FieldPromptSnapshot, intelcheckresult.FieldRawReply, intelcheckresult.FieldExtractedAnswer, intelcheckresult.FieldHTMLOutput, intelcheckresult.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case intelcheckresult.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntelCheckResult fields.
func (_m *IntelCheckResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intelcheckresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case intelcheckresult.FieldRoundID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_id", values[i])
			} else if value.Valid {
				_m.RoundID = value.Int64
			}
		case intelcheckresult.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.Int64
			}
		case intelcheckresult.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = intelcheckresult.Kind(value.String)
			}
		case intelcheckresult.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = intelcheckresult.Status(value.String)
			}
		case intelcheckresult.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = new(int)
				*_m.LatencyMs = int(value.Int64)
			}
		case intelcheckresult.FieldPromptSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_snapshot", values[i])
			} else if value.Valid {
				_m.PromptSnapshot = value.String
			}
		case intelcheckresult.FieldRawReply:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_reply", values[i])
			} else if value.Valid {
				_m.RawReply = value.String
			}
		case intelcheckresult.FieldExtractedAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extracted_answer", values[i])
			} else if value.Valid {
				_m.ExtractedAnswer = value.String
			}
		case intelcheckresult.FieldHTMLOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field html_output", values[i])
			} else if value.Valid {
				_m.HTMLOutput = value.String
			}
		case intelcheckresult.FieldJudgeDetail:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field judge_detail", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.JudgeDetail); err != nil {
					return fmt.Errorf("unmarshal field judge_detail: %w", err)
				}
			}
		case intelcheckresult.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case intelcheckresult.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = new(int)
				*_m.InputTokens = int(value.Int64)
			}
		case intelcheckresult.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = new(int)
				*_m.OutputTokens = int(value.Int64)
			}
		case intelcheckresult.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntelCheckResult.
// This includes values selected through modifiers, order, etc.
func (_m *IntelCheckResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRound queries the "round" edge of the IntelCheckResult entity.
func (_m *IntelCheckResult) QueryRound() *IntelCheckRoundQuery {
	return NewIntelCheckResultClient(_m.config).QueryRound(_m)
}

// QueryTarget queries the "target" edge of the IntelCheckResult entity.
func (_m *IntelCheckResult) QueryTarget() *IntelCheckTargetQuery {
	return NewIntelCheckResultClient(_m.config).QueryTarget(_m)
}

// Update returns a builder for updating this IntelCheckResult.
// Note that you need to call IntelCheckResult.Unwrap() before calling this method if this IntelCheckResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntelCheckResult) Update() *IntelCheckResultUpdateOne {
	return NewIntelCheckResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntelCheckResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntelCheckResult) Unwrap() *IntelCheckResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntelCheckResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntelCheckResult) String() string {
	var builder strings.Builder
	builder.WriteString("IntelCheckResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("round_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoundID))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.LatencyMs; v != nil {
		builder.WriteString("latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("prompt_snapshot=")
	builder.WriteString(_m.PromptSnapshot)
	builder.WriteString(", ")
	builder.WriteString("raw_reply=")
	builder.WriteString(_m.RawReply)
	builder.WriteString(", ")
	builder.WriteString("extracted_answer=")
	builder.WriteString(_m.ExtractedAnswer)
	builder.WriteString(", ")
	builder.WriteString("html_output=")
	builder.WriteString(_m.HTMLOutput)
	builder.WriteString(", ")
	builder.WriteString("judge_detail=")
	builder.WriteString(fmt.Sprintf("%v", _m.JudgeDetail))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	if v := _m.InputTokens; v != nil {
		builder.WriteString("input_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputTokens; v != nil {
		builder.WriteString("output_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IntelCheckResults is a parsable slice of IntelCheckResult.
type IntelCheckResults []*IntelCheckResult
