// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckresult"
	"github.com/Wei-Shaw/sub2api/ent/intelchecktarget"
)

// IntelCheckTargetCreate is the builder for creating a IntelCheckTarget entity.
type IntelCheckTargetCreate struct {
	config
	mutation *IntelCheckTargetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntelCheckTargetCreate) SetCreatedAt(v time.Time) *IntelCheckTargetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableCreatedAt(v *time.Time) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntelCheckTargetCreate) SetUpdatedAt(v time.Time) *IntelCheckTargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableUpdatedAt(v *time.Time) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *IntelCheckTargetCreate) SetName(v string) *IntelCheckTargetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *IntelCheckTargetCreate) SetDescription(v string) *IntelCheckTargetCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableDescription(v *string) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *IntelCheckTargetCreate) SetBaseURL(v string) *IntelCheckTargetCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_c *IntelCheckTargetCreate) SetAPIKeyEncrypted(v string) *IntelCheckTargetCreate {
	_c.mutation.SetAPIKeyEncrypted(v)
	return _c
}

// SetAPIMode sets the "api_mode" field.
func (_c *IntelCheckTargetCreate) SetAPIMode(v string) *IntelCheckTargetCreate {
	_c.mutation.SetAPIMode(v)
	return _c
}

// SetNillableAPIMode sets the "api_mode" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableAPIMode(v *string) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetAPIMode(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *IntelCheckTargetCreate) SetModel(v string) *IntelCheckTargetCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_c *IntelCheckTargetCreate) SetReasoningEffort(v string) *IntelCheckTargetCreate {
	_c.mutation.SetReasoningEffort(v)
	return _c
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableReasoningEffort(v *string) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetReasoningEffort(*v)
	}
	return _c
}

// SetRateLabel sets the "rate_label" field.
func (_c *IntelCheckTargetCreate) SetRateLabel(v string) *IntelCheckTargetCreate {
	_c.mutation.SetRateLabel(v)
	return _c
}

// SetNillableRateLabel sets the "rate_label" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableRateLabel(v *string) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetRateLabel(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *IntelCheckTargetCreate) SetEnabled(v bool) *IntelCheckTargetCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableEnabled(v *bool) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *IntelCheckTargetCreate) SetSortOrder(v int) *IntelCheckTargetCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *IntelCheckTargetCreate) SetNillableSortOrder(v *int) *IntelCheckTargetCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *IntelCheckTargetCreate) SetCreatedBy(v int64) *IntelCheckTargetCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// AddResultIDs adds the "results" edge to the IntelCheckResult entity by IDs.
func (_c *IntelCheckTargetCreate) AddResultIDs(ids ...int64) *IntelCheckTargetCreate {
	_c.mutation.AddResultIDs(ids...)
	return _c
}

// AddResults adds the "results" edges to the IntelCheckResult entity.
func (_c *IntelCheckTargetCreate) AddResults(v ...*IntelCheckResult) *IntelCheckTargetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResultIDs(ids...)
}

// Mutation returns the IntelCheckTargetMutation object of the builder.
func (_c *IntelCheckTargetCreate) Mutation() *IntelCheckTargetMutation {
	return _c.mutation
}

// Save creates the IntelCheckTarget in the database.
func (_c *IntelCheckTargetCreate) Save(ctx context.Context) (*IntelCheckTarget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntelCheckTargetCreate) SaveX(ctx context.Context) *IntelCheckTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelCheckTargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelCheckTargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntelCheckTargetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := intelchecktarget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := intelchecktarget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := intelchecktarget.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.APIMode(); !ok {
		v := intelchecktarget.DefaultAPIMode
		_c.mutation.SetAPIMode(v)
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		v := intelchecktarget.DefaultReasoningEffort
		_c.mutation.SetReasoningEffort(v)
	}
	if _, ok := _c.mutation.RateLabel(); !ok {
		v := intelchecktarget.DefaultRateLabel
		_c.mutation.SetRateLabel(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := intelchecktarget.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := intelchecktarget.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntelCheckTargetCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IntelCheckTarget.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IntelCheckTarget.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IntelCheckTarget.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := intelchecktarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := intelchecktarget.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "IntelCheckTarget.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := intelchecktarget.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyEncrypted(); !ok {
		return &ValidationError{Name: "api_key_encrypted", err: errors.New(`ent: missing required field "IntelCheckTarget.api_key_encrypted"`)}
	}
	if v, ok := _c.mutation.APIKeyEncrypted(); ok {
		if err := intelchecktarget.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_key_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIMode(); !ok {
		return &ValidationError{Name: "api_mode", err: errors.New(`ent: missing required field "IntelCheckTarget.api_mode"`)}
	}
	if v, ok := _c.mutation.APIMode(); ok {
		if err := intelchecktarget.APIModeValidator(v); err != nil {
			return &ValidationError{Name: "api_mode", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "IntelCheckTarget.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := intelchecktarget.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		return &ValidationError{Name: "reasoning_effort", err: errors.New(`ent: missing required field "IntelCheckTarget.reasoning_effort"`)}
	}
	if v, ok := _c.mutation.ReasoningEffort(); ok {
		if err := intelchecktarget.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RateLabel(); ok {
		if err := intelchecktarget.RateLabelValidator(v); err != nil {
			return &ValidationError{Name: "rate_label", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.rate_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "IntelCheckTarget.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "IntelCheckTarget.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "IntelCheckTarget.created_by"`)}
	}
	return nil
}

func (_c *IntelCheckTargetCreate) sqlSave(ctx context.Context) (*IntelCheckTarget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntelCheckTargetCreate) createSpec() (*IntelCheckTarget, *sqlgraph.CreateSpec) {
	var (
		_node = &IntelCheckTarget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(intelchecktarget.Table, sqlgraph.NewFieldSpec(intelchecktarget.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(intelchecktarget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(intelchecktarget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(intelchecktarget.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(intelchecktarget.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(intelchecktarget.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(intelchecktarget.FieldAPIKeyEncrypted, field.TypeString, value)
		_node.APIKeyEncrypted = value
	}
	if value, ok := _c.mutation.APIMode(); ok {
		_spec.SetField(intelchecktarget.FieldAPIMode, field.TypeString, value)
		_node.APIMode = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(intelchecktarget.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.ReasoningEffort(); ok {
		_spec.SetField(intelchecktarget.FieldReasoningEffort, field.TypeString, value)
		_node.ReasoningEffort = value
	}
	if value, ok := _c.mutation.RateLabel(); ok {
		_spec.SetField(intelchecktarget.FieldRateLabel, field.TypeString, value)
		_node.RateLabel = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(intelchecktarget.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(intelchecktarget.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(intelchecktarget.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if nodes := _c.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelCheckTarget.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelCheckTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelCheckTargetCreate) OnConflict(opts ...sql.ConflictOption) *IntelCheckTargetUpsertOne {
	_c.conflict = opts
	return &IntelCheckTargetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelCheckTargetCreate) OnConflictColumns(columns ...string) *IntelCheckTargetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelCheckTargetUpsertOne{
		create: _c,
	}
}

type (
	// IntelCheckTargetUpsertOne is the builder for "upsert"-ing
	//  one IntelCheckTarget node.
	IntelCheckTargetUpsertOne struct {
		create *IntelCheckTargetCreate
	}

	// IntelCheckTargetUpsert is the "OnConflict" setter.
	IntelCheckTargetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckTargetUpsert) SetUpdatedAt(v time.Time) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateUpdatedAt() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *IntelCheckTargetUpsert) SetName(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateName() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *IntelCheckTargetUpsert) SetDescription(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateDescription() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *IntelCheckTargetUpsert) ClearDescription() *IntelCheckTargetUpsert {
	u.SetNull(intelchecktarget.FieldDescription)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *IntelCheckTargetUpsert) SetBaseURL(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateBaseURL() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldBaseURL)
	return u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *IntelCheckTargetUpsert) SetAPIKeyEncrypted(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldAPIKeyEncrypted, v)
	return u
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateAPIKeyEncrypted() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldAPIKeyEncrypted)
	return u
}

// SetAPIMode sets the "api_mode" field.
func (u *IntelCheckTargetUpsert) SetAPIMode(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldAPIMode, v)
	return u
}

// UpdateAPIMode sets the "api_mode" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateAPIMode() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldAPIMode)
	return u
}

// SetModel sets the "model" field.
func (u *IntelCheckTargetUpsert) SetModel(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateModel() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldModel)
	return u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelCheckTargetUpsert) SetReasoningEffort(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldReasoningEffort, v)
	return u
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateReasoningEffort() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldReasoningEffort)
	return u
}

// SetRateLabel sets the "rate_label" field.
func (u *IntelCheckTargetUpsert) SetRateLabel(v string) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldRateLabel, v)
	return u
}

// UpdateRateLabel sets the "rate_label" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateRateLabel() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldRateLabel)
	return u
}

// ClearRateLabel clears the value of the "rate_label" field.
func (u *IntelCheckTargetUpsert) ClearRateLabel() *IntelCheckTargetUpsert {
	u.SetNull(intelchecktarget.FieldRateLabel)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckTargetUpsert) SetEnabled(v bool) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateEnabled() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *IntelCheckTargetUpsert) SetSortOrder(v int) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateSortOrder() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *IntelCheckTargetUpsert) AddSortOrder(v int) *IntelCheckTargetUpsert {
	u.Add(intelchecktarget.FieldSortOrder, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *IntelCheckTargetUpsert) SetCreatedBy(v int64) *IntelCheckTargetUpsert {
	u.Set(intelchecktarget.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IntelCheckTargetUpsert) UpdateCreatedBy() *IntelCheckTargetUpsert {
	u.SetExcluded(intelchecktarget.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IntelCheckTargetUpsert) AddCreatedBy(v int64) *IntelCheckTargetUpsert {
	u.Add(intelchecktarget.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelCheckTargetUpsertOne) UpdateNewValues() *IntelCheckTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(intelchecktarget.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IntelCheckTargetUpsertOne) Ignore() *IntelCheckTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelCheckTargetUpsertOne) DoNothing() *IntelCheckTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelCheckTargetCreate.OnConflict
// documentation for more info.
func (u *IntelCheckTargetUpsertOne) Update(set func(*IntelCheckTargetUpsert)) *IntelCheckTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelCheckTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckTargetUpsertOne) SetUpdatedAt(v time.Time) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateUpdatedAt() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *IntelCheckTargetUpsertOne) SetName(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateName() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *IntelCheckTargetUpsertOne) SetDescription(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateDescription() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *IntelCheckTargetUpsertOne) ClearDescription() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.ClearDescription()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *IntelCheckTargetUpsertOne) SetBaseURL(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateBaseURL() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *IntelCheckTargetUpsertOne) SetAPIKeyEncrypted(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateAPIKeyEncrypted() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetAPIMode sets the "api_mode" field.
func (u *IntelCheckTargetUpsertOne) SetAPIMode(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetAPIMode(v)
	})
}

// UpdateAPIMode sets the "api_mode" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateAPIMode() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateAPIMode()
	})
}

// SetModel sets the "model" field.
func (u *IntelCheckTargetUpsertOne) SetModel(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateModel() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateModel()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelCheckTargetUpsertOne) SetReasoningEffort(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateReasoningEffort() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetRateLabel sets the "rate_label" field.
func (u *IntelCheckTargetUpsertOne) SetRateLabel(v string) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetRateLabel(v)
	})
}

// UpdateRateLabel sets the "rate_label" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateRateLabel() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateRateLabel()
	})
}

// ClearRateLabel clears the value of the "rate_label" field.
func (u *IntelCheckTargetUpsertOne) ClearRateLabel() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.ClearRateLabel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckTargetUpsertOne) SetEnabled(v bool) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateEnabled() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *IntelCheckTargetUpsertOne) SetSortOrder(v int) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *IntelCheckTargetUpsertOne) AddSortOrder(v int) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateSortOrder() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IntelCheckTargetUpsertOne) SetCreatedBy(v int64) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IntelCheckTargetUpsertOne) AddCreatedBy(v int64) *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertOne) UpdateCreatedBy() *IntelCheckTargetUpsertOne {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *IntelCheckTargetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelCheckTargetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelCheckTargetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IntelCheckTargetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IntelCheckTargetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IntelCheckTargetCreateBulk is the builder for creating many IntelCheckTarget entities in bulk.
type IntelCheckTargetCreateBulk struct {
	config
	err      error
	builders []*IntelCheckTargetCreate
	conflict []sql.ConflictOption
}

// Save creates the IntelCheckTarget entities in the database.
func (_c *IntelCheckTargetCreateBulk) Save(ctx context.Context) ([]*IntelCheckTarget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntelCheckTarget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntelCheckTargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntelCheckTargetCreateBulk) SaveX(ctx context.Context) []*IntelCheckTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntelCheckTargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntelCheckTargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IntelCheckTarget.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IntelCheckTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *IntelCheckTargetCreateBulk) OnConflict(opts ...sql.ConflictOption) *IntelCheckTargetUpsertBulk {
	_c.conflict = opts
	return &IntelCheckTargetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IntelCheckTargetCreateBulk) OnConflictColumns(columns ...string) *IntelCheckTargetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IntelCheckTargetUpsertBulk{
		create: _c,
	}
}

// IntelCheckTargetUpsertBulk is the builder for "upsert"-ing
// a bulk of IntelCheckTarget nodes.
type IntelCheckTargetUpsertBulk struct {
	create *IntelCheckTargetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IntelCheckTargetUpsertBulk) UpdateNewValues() *IntelCheckTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(intelchecktarget.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IntelCheckTarget.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IntelCheckTargetUpsertBulk) Ignore() *IntelCheckTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IntelCheckTargetUpsertBulk) DoNothing() *IntelCheckTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IntelCheckTargetCreateBulk.OnConflict
// documentation for more info.
func (u *IntelCheckTargetUpsertBulk) Update(set func(*IntelCheckTargetUpsert)) *IntelCheckTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IntelCheckTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IntelCheckTargetUpsertBulk) SetUpdatedAt(v time.Time) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateUpdatedAt() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *IntelCheckTargetUpsertBulk) SetName(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateName() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *IntelCheckTargetUpsertBulk) SetDescription(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateDescription() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *IntelCheckTargetUpsertBulk) ClearDescription() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.ClearDescription()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *IntelCheckTargetUpsertBulk) SetBaseURL(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateBaseURL() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (u *IntelCheckTargetUpsertBulk) SetAPIKeyEncrypted(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetAPIKeyEncrypted(v)
	})
}

// UpdateAPIKeyEncrypted sets the "api_key_encrypted" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateAPIKeyEncrypted() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateAPIKeyEncrypted()
	})
}

// SetAPIMode sets the "api_mode" field.
func (u *IntelCheckTargetUpsertBulk) SetAPIMode(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetAPIMode(v)
	})
}

// UpdateAPIMode sets the "api_mode" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateAPIMode() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateAPIMode()
	})
}

// SetModel sets the "model" field.
func (u *IntelCheckTargetUpsertBulk) SetModel(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateModel() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateModel()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *IntelCheckTargetUpsertBulk) SetReasoningEffort(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateReasoningEffort() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateReasoningEffort()
	})
}

// SetRateLabel sets the "rate_label" field.
func (u *IntelCheckTargetUpsertBulk) SetRateLabel(v string) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetRateLabel(v)
	})
}

// UpdateRateLabel sets the "rate_label" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateRateLabel() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateRateLabel()
	})
}

// ClearRateLabel clears the value of the "rate_label" field.
func (u *IntelCheckTargetUpsertBulk) ClearRateLabel() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.ClearRateLabel()
	})
}

// SetEnabled sets the "enabled" field.
func (u *IntelCheckTargetUpsertBulk) SetEnabled(v bool) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateEnabled() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *IntelCheckTargetUpsertBulk) SetSortOrder(v int) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *IntelCheckTargetUpsertBulk) AddSortOrder(v int) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateSortOrder() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *IntelCheckTargetUpsertBulk) SetCreatedBy(v int64) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *IntelCheckTargetUpsertBulk) AddCreatedBy(v int64) *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *IntelCheckTargetUpsertBulk) UpdateCreatedBy() *IntelCheckTargetUpsertBulk {
	return u.Update(func(s *IntelCheckTargetUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *IntelCheckTargetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IntelCheckTargetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IntelCheckTargetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IntelCheckTargetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
