// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckquestion"
)

// IntelCheckQuestion is the model entity for the IntelCheckQuestion schema.
type IntelCheckQuestion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind intelcheckquestion.Kind `json:"kind,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// ExpectedAnswer holds the value of the "expected_answer" field.
	ExpectedAnswer string `json:"expected_answer,omitempty"`
	// Answer match mode: exact, numeric, contains or regex
	MatchMode string `json:"match_mode,omitempty"`
	// ReferenceHTML holds the value of the "reference_html" field.
	ReferenceHTML string `json:"reference_html,omitempty"`
	// ReferenceMetrics holds the value of the "reference_metrics" field.
	ReferenceMetrics map[string]interface{} `json:"reference_metrics,omitempty"`
	// DrawingRules holds the value of the "drawing_rules" field.
	DrawingRules map[string]interface{} `json:"drawing_rules,omitempty"`
	// ReviewRubric holds the value of the "review_rubric" field.
	ReviewRubric string `json:"review_rubric,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntelCheckQuestion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intelcheckquestion.FieldReferenceMetrics, intelcheckquestion.FieldDrawingRules:
			values[i] = new([]byte)
		case intelcheckquestion.FieldEnabled:
			values[i] = new(sql.NullBool)
		case intelcheckquestion.FieldID:
			values[i] = new(sql.NullInt64)
		case intelcheckquestion.FieldKind, intelcheckquestion.FieldTitle, intelcheckquestion.FieldPrompt, intelcheckquestion.FieldExpectedAnswer, intelcheckquestion.FieldMatchMode, intelcheckquestion.FieldReferenceHTML, intelcheckquestion.FieldReviewRubric:
			values[i] = new(sql.NullString)
		case intelcheckquestion.FieldCreatedAt, intelcheckquestion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntelCheckQuestion fields.
func (_m *IntelCheckQuestion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intelcheckquestion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case intelcheckquestion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intelcheckquestion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case intelcheckquestion.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = intelcheckquestion.Kind(value.String)
			}
		case intelcheckquestion.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case intelcheckquestion.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case intelcheckquestion.FieldExpectedAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expected_answer", values[i])
			} else if value.Valid {
				_m.ExpectedAnswer = value.String
			}
		case intelcheckquestion.FieldMatchMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_mode", values[i])
			} else if value.Valid {
				_m.MatchMode = value.String
			}
		case intelcheckquestion.FieldReferenceHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_html", values[i])
			} else if value.Valid {
				_m.ReferenceHTML = value.String
			}
		case intelcheckquestion.FieldReferenceMetrics:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reference_metrics", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ReferenceMetrics); err != nil {
					return fmt.Errorf("unmarshal field reference_metrics: %w", err)
				}
			}
		case intelcheckquestion.FieldDrawingRules:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field drawing_rules", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DrawingRules); err != nil {
					return fmt.Errorf("unmarshal field drawing_rules: %w", err)
				}
			}
		case intelcheckquestion.FieldReviewRubric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_rubric", values[i])
			} else if value.Valid {
				_m.ReviewRubric = value.String
			}
		case intelcheckquestion.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntelCheckQuestion.
// This includes values selected through modifiers, order, etc.
func (_m *IntelCheckQuestion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntelCheckQuestion.
// Note that you need to call IntelCheckQuestion.Unwrap() before calling this method if this IntelCheckQuestion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntelCheckQuestion) Update() *IntelCheckQuestionUpdateOne {
	return NewIntelCheckQuestionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntelCheckQuestion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntelCheckQuestion) Unwrap() *IntelCheckQuestion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntelCheckQuestion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntelCheckQuestion) String() string {
	var builder strings.Builder
	builder.WriteString("IntelCheckQuestion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("expected_answer=")
	builder.WriteString(_m.ExpectedAnswer)
	builder.WriteString(", ")
	builder.WriteString("match_mode=")
	builder.WriteString(_m.MatchMode)
	builder.WriteString(", ")
	builder.WriteString("reference_html=")
	builder.WriteString(_m.ReferenceHTML)
	builder.WriteString(", ")
	builder.WriteString("reference_metrics=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceMetrics))
	builder.WriteString(", ")
	builder.WriteString("drawing_rules=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrawingRules))
	builder.WriteString(", ")
	builder.WriteString("review_rubric=")
	builder.WriteString(_m.ReviewRubric)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// IntelCheckQuestions is a parsable slice of IntelCheckQuestion.
type IntelCheckQuestions []*IntelCheckQuestion
