// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/intelcheckresult"
	"github.com/Wei-Shaw/sub2api/ent/intelchecktarget"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// IntelCheckTargetUpdate is the builder for updating IntelCheckTarget entities.
type IntelCheckTargetUpdate struct {
	config
	hooks    []Hook
	mutation *IntelCheckTargetMutation
}

// Where appends a list predicates to the IntelCheckTargetUpdate builder.
func (_u *IntelCheckTargetUpdate) Where(ps ...predicate.IntelCheckTarget) *IntelCheckTargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntelCheckTargetUpdate) SetUpdatedAt(v time.Time) *IntelCheckTargetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *IntelCheckTargetUpdate) SetName(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableName(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IntelCheckTargetUpdate) SetDescription(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableDescription(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *IntelCheckTargetUpdate) ClearDescription() *IntelCheckTargetUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *IntelCheckTargetUpdate) SetBaseURL(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableBaseURL(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *IntelCheckTargetUpdate) SetAPIKeyEncrypted(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableAPIKeyEncrypted(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetAPIMode sets the "api_mode" field.
func (_u *IntelCheckTargetUpdate) SetAPIMode(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetAPIMode(v)
	return _u
}

// SetNillableAPIMode sets the "api_mode" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableAPIMode(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetAPIMode(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *IntelCheckTargetUpdate) SetModel(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableModel(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *IntelCheckTargetUpdate) SetReasoningEffort(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableReasoningEffort(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetRateLabel sets the "rate_label" field.
func (_u *IntelCheckTargetUpdate) SetRateLabel(v string) *IntelCheckTargetUpdate {
	_u.mutation.SetRateLabel(v)
	return _u
}

// SetNillableRateLabel sets the "rate_label" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableRateLabel(v *string) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetRateLabel(*v)
	}
	return _u
}

// ClearRateLabel clears the value of the "rate_label" field.
func (_u *IntelCheckTargetUpdate) ClearRateLabel() *IntelCheckTargetUpdate {
	_u.mutation.ClearRateLabel()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntelCheckTargetUpdate) SetEnabled(v bool) *IntelCheckTargetUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableEnabled(v *bool) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *IntelCheckTargetUpdate) SetSortOrder(v int) *IntelCheckTargetUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableSortOrder(v *int) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *IntelCheckTargetUpdate) AddSortOrder(v int) *IntelCheckTargetUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IntelCheckTargetUpdate) SetCreatedBy(v int64) *IntelCheckTargetUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IntelCheckTargetUpdate) SetNillableCreatedBy(v *int64) *IntelCheckTargetUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *IntelCheckTargetUpdate) AddCreatedBy(v int64) *IntelCheckTargetUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddResultIDs adds the "results" edge to the IntelCheckResult entity by IDs.
func (_u *IntelCheckTargetUpdate) AddResultIDs(ids ...int64) *IntelCheckTargetUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the IntelCheckResult entity.
func (_u *IntelCheckTargetUpdate) AddResults(v ...*IntelCheckResult) *IntelCheckTargetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the IntelCheckTargetMutation object of the builder.
func (_u *IntelCheckTargetUpdate) Mutation() *IntelCheckTargetMutation {
	return _u.mutation
}

// ClearResults clears all "results" edges to the IntelCheckResult entity.
func (_u *IntelCheckTargetUpdate) ClearResults() *IntelCheckTargetUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to IntelCheckResult entities by IDs.
func (_u *IntelCheckTargetUpdate) RemoveResultIDs(ids ...int64) *IntelCheckTargetUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to IntelCheckResult entities.
func (_u *IntelCheckTargetUpdate) RemoveResults(v ...*IntelCheckResult) *IntelCheckTargetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntelCheckTargetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelCheckTargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntelCheckTargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelCheckTargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntelCheckTargetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intelchecktarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelCheckTargetUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := intelchecktarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := intelchecktarget.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := intelchecktarget.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := intelchecktarget.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMode(); ok {
		if err := intelchecktarget.APIModeValidator(v); err != nil {
			return &ValidationError{Name: "api_mode", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := intelchecktarget.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := intelchecktarget.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateLabel(); ok {
		if err := intelchecktarget.RateLabelValidator(v); err != nil {
			return &ValidationError{Name: "rate_label", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.rate_label": %w`, err)}
		}
	}
	return nil
}

func (_u *IntelCheckTargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intelchecktarget.Table, intelchecktarget.Columns, sqlgraph.NewFieldSpec(intelchecktarget.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intelchecktarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(intelchecktarget.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(intelchecktarget.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(intelchecktarget.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(intelchecktarget.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(intelchecktarget.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIMode(); ok {
		_spec.SetField(intelchecktarget.FieldAPIMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(intelchecktarget.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(intelchecktarget.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateLabel(); ok {
		_spec.SetField(intelchecktarget.FieldRateLabel, field.TypeString, value)
	}
	if _u.mutation.RateLabelCleared() {
		_spec.ClearField(intelchecktarget.FieldRateLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(intelchecktarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(intelchecktarget.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(intelchecktarget.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(intelchecktarget.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(intelchecktarget.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intelchecktarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntelCheckTargetUpdateOne is the builder for updating a single IntelCheckTarget entity.
type IntelCheckTargetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntelCheckTargetMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntelCheckTargetUpdateOne) SetUpdatedAt(v time.Time) *IntelCheckTargetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *IntelCheckTargetUpdateOne) SetName(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableName(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *IntelCheckTargetUpdateOne) SetDescription(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableDescription(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *IntelCheckTargetUpdateOne) ClearDescription() *IntelCheckTargetUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *IntelCheckTargetUpdateOne) SetBaseURL(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableBaseURL(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *IntelCheckTargetUpdateOne) SetAPIKeyEncrypted(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableAPIKeyEncrypted(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetAPIMode sets the "api_mode" field.
func (_u *IntelCheckTargetUpdateOne) SetAPIMode(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetAPIMode(v)
	return _u
}

// SetNillableAPIMode sets the "api_mode" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableAPIMode(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetAPIMode(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *IntelCheckTargetUpdateOne) SetModel(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableModel(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *IntelCheckTargetUpdateOne) SetReasoningEffort(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableReasoningEffort(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetRateLabel sets the "rate_label" field.
func (_u *IntelCheckTargetUpdateOne) SetRateLabel(v string) *IntelCheckTargetUpdateOne {
	_u.mutation.SetRateLabel(v)
	return _u
}

// SetNillableRateLabel sets the "rate_label" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableRateLabel(v *string) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetRateLabel(*v)
	}
	return _u
}

// ClearRateLabel clears the value of the "rate_label" field.
func (_u *IntelCheckTargetUpdateOne) ClearRateLabel() *IntelCheckTargetUpdateOne {
	_u.mutation.ClearRateLabel()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *IntelCheckTargetUpdateOne) SetEnabled(v bool) *IntelCheckTargetUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableEnabled(v *bool) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *IntelCheckTargetUpdateOne) SetSortOrder(v int) *IntelCheckTargetUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableSortOrder(v *int) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *IntelCheckTargetUpdateOne) AddSortOrder(v int) *IntelCheckTargetUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *IntelCheckTargetUpdateOne) SetCreatedBy(v int64) *IntelCheckTargetUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *IntelCheckTargetUpdateOne) SetNillableCreatedBy(v *int64) *IntelCheckTargetUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *IntelCheckTargetUpdateOne) AddCreatedBy(v int64) *IntelCheckTargetUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// AddResultIDs adds the "results" edge to the IntelCheckResult entity by IDs.
func (_u *IntelCheckTargetUpdateOne) AddResultIDs(ids ...int64) *IntelCheckTargetUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the IntelCheckResult entity.
func (_u *IntelCheckTargetUpdateOne) AddResults(v ...*IntelCheckResult) *IntelCheckTargetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the IntelCheckTargetMutation object of the builder.
func (_u *IntelCheckTargetUpdateOne) Mutation() *IntelCheckTargetMutation {
	return _u.mutation
}

// ClearResults clears all "results" edges to the IntelCheckResult entity.
func (_u *IntelCheckTargetUpdateOne) ClearResults() *IntelCheckTargetUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to IntelCheckResult entities by IDs.
func (_u *IntelCheckTargetUpdateOne) RemoveResultIDs(ids ...int64) *IntelCheckTargetUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to IntelCheckResult entities.
func (_u *IntelCheckTargetUpdateOne) RemoveResults(v ...*IntelCheckResult) *IntelCheckTargetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Where appends a list predicates to the IntelCheckTargetUpdate builder.
func (_u *IntelCheckTargetUpdateOne) Where(ps ...predicate.IntelCheckTarget) *IntelCheckTargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntelCheckTargetUpdateOne) Select(field string, fields ...string) *IntelCheckTargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntelCheckTarget entity.
func (_u *IntelCheckTargetUpdateOne) Save(ctx context.Context) (*IntelCheckTarget, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntelCheckTargetUpdateOne) SaveX(ctx context.Context) *IntelCheckTarget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntelCheckTargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntelCheckTargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntelCheckTargetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intelchecktarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntelCheckTargetUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := intelchecktarget.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := intelchecktarget.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := intelchecktarget.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := intelchecktarget.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIMode(); ok {
		if err := intelchecktarget.APIModeValidator(v); err != nil {
			return &ValidationError{Name: "api_mode", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.api_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := intelchecktarget.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := intelchecktarget.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.reasoning_effort": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateLabel(); ok {
		if err := intelchecktarget.RateLabelValidator(v); err != nil {
			return &ValidationError{Name: "rate_label", err: fmt.Errorf(`ent: validator failed for field "IntelCheckTarget.rate_label": %w`, err)}
		}
	}
	return nil
}

func (_u *IntelCheckTargetUpdateOne) sqlSave(ctx context.Context) (_node *IntelCheckTarget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intelchecktarget.Table, intelchecktarget.Columns, sqlgraph.NewFieldSpec(intelchecktarget.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntelCheckTarget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, intelchecktarget.FieldID)
		for _, f := range fields {
			if !intelchecktarget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != intelchecktarget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intelchecktarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(intelchecktarget.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(intelchecktarget.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(intelchecktarget.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(intelchecktarget.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(intelchecktarget.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIMode(); ok {
		_spec.SetField(intelchecktarget.FieldAPIMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(intelchecktarget.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(intelchecktarget.FieldReasoningEffort, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateLabel(); ok {
		_spec.SetField(intelchecktarget.FieldRateLabel, field.TypeString, value)
	}
	if _u.mutation.RateLabelCleared() {
		_spec.ClearField(intelchecktarget.FieldRateLabel, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(intelchecktarget.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(intelchecktarget.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(intelchecktarget.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(intelchecktarget.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(intelchecktarget.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   intelchecktarget.ResultsTable,
			Columns: []string{intelchecktarget.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(intelcheckresult.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IntelCheckTarget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intelchecktarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
