// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/packagefreezeday"
)

// PackageFreezeDayCreate is the builder for creating a PackageFreezeDay entity.
type PackageFreezeDayCreate struct {
	config
	mutation *PackageFreezeDayMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PackageFreezeDayCreate) SetCreatedAt(v time.Time) *PackageFreezeDayCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PackageFreezeDayCreate) SetNillableCreatedAt(v *time.Time) *PackageFreezeDayCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PackageFreezeDayCreate) SetUpdatedAt(v time.Time) *PackageFreezeDayCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PackageFreezeDayCreate) SetNillableUpdatedAt(v *time.Time) *PackageFreezeDayCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDay sets the "day" field.
func (_c *PackageFreezeDayCreate) SetDay(v time.Time) *PackageFreezeDayCreate {
	_c.mutation.SetDay(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PackageFreezeDayCreate) SetName(v string) *PackageFreezeDayCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PackageFreezeDayCreate) SetNillableName(v *string) *PackageFreezeDayCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *PackageFreezeDayCreate) SetKind(v string) *PackageFreezeDayCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *PackageFreezeDayCreate) SetSource(v string) *PackageFreezeDayCreate {
	_c.mutation.SetSource(v)
	return _c
}

// Mutation returns the PackageFreezeDayMutation object of the builder.
func (_c *PackageFreezeDayCreate) Mutation() *PackageFreezeDayMutation {
	return _c.mutation
}

// Save creates the PackageFreezeDay in the database.
func (_c *PackageFreezeDayCreate) Save(ctx context.Context) (*PackageFreezeDay, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PackageFreezeDayCreate) SaveX(ctx context.Context) *PackageFreezeDay {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageFreezeDayCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageFreezeDayCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PackageFreezeDayCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := packagefreezeday.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := packagefreezeday.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := packagefreezeday.DefaultName
		_c.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PackageFreezeDayCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PackageFreezeDay.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PackageFreezeDay.updated_at"`)}
	}
	if _, ok := _c.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "PackageFreezeDay.day"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PackageFreezeDay.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := packagefreezeday.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PackageFreezeDay.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "PackageFreezeDay.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := packagefreezeday.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "PackageFreezeDay.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "PackageFreezeDay.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := packagefreezeday.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "PackageFreezeDay.source": %w`, err)}
		}
	}
	return nil
}

func (_c *PackageFreezeDayCreate) sqlSave(ctx context.Context) (*PackageFreezeDay, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PackageFreezeDayCreate) createSpec() (*PackageFreezeDay, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageFreezeDay{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(packagefreezeday.Table, sqlgraph.NewFieldSpec(packagefreezeday.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(packagefreezeday.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(packagefreezeday.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Day(); ok {
		_spec.SetField(packagefreezeday.FieldDay, field.TypeTime, value)
		_node.Day = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(packagefreezeday.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(packagefreezeday.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(packagefreezeday.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackageFreezeDay.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackageFreezeDayUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackageFreezeDayCreate) OnConflict(opts ...sql.ConflictOption) *PackageFreezeDayUpsertOne {
	_c.conflict = opts
	return &PackageFreezeDayUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackageFreezeDayCreate) OnConflictColumns(columns ...string) *PackageFreezeDayUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackageFreezeDayUpsertOne{
		create: _c,
	}
}

type (
	// PackageFreezeDayUpsertOne is the builder for "upsert"-ing
	//  one PackageFreezeDay node.
	PackageFreezeDayUpsertOne struct {
		create *PackageFreezeDayCreate
	}

	// PackageFreezeDayUpsert is the "OnConflict" setter.
	PackageFreezeDayUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageFreezeDayUpsert) SetUpdatedAt(v time.Time) *PackageFreezeDayUpsert {
	u.Set(packagefreezeday.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageFreezeDayUpsert) UpdateUpdatedAt() *PackageFreezeDayUpsert {
	u.SetExcluded(packagefreezeday.FieldUpdatedAt)
	return u
}

// SetDay sets the "day" field.
func (u *PackageFreezeDayUpsert) SetDay(v time.Time) *PackageFreezeDayUpsert {
	u.Set(packagefreezeday.FieldDay, v)
	return u
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *PackageFreezeDayUpsert) UpdateDay() *PackageFreezeDayUpsert {
	u.SetExcluded(packagefreezeday.FieldDay)
	return u
}

// SetName sets the "name" field.
func (u *PackageFreezeDayUpsert) SetName(v string) *PackageFreezeDayUpsert {
	u.Set(packagefreezeday.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackageFreezeDayUpsert) UpdateName() *PackageFreezeDayUpsert {
	u.SetExcluded(packagefreezeday.FieldName)
	return u
}

// SetKind sets the "kind" field.
func (u *PackageFreezeDayUpsert) SetKind(v string) *PackageFreezeDayUpsert {
	u.Set(packagefreezeday.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PackageFreezeDayUpsert) UpdateKind() *PackageFreezeDayUpsert {
	u.SetExcluded(packagefreezeday.FieldKind)
	return u
}

// SetSource sets the "source" field.
func (u *PackageFreezeDayUpsert) SetSource(v string) *PackageFreezeDayUpsert {
	u.Set(packagefreezeday.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *PackageFreezeDayUpsert) UpdateSource() *PackageFreezeDayUpsert {
	u.SetExcluded(packagefreezeday.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackageFreezeDayUpsertOne) UpdateNewValues() *PackageFreezeDayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(packagefreezeday.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PackageFreezeDayUpsertOne) Ignore() *PackageFreezeDayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackageFreezeDayUpsertOne) DoNothing() *PackageFreezeDayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackageFreezeDayCreate.OnConflict
// documentation for more info.
func (u *PackageFreezeDayUpsertOne) Update(set func(*PackageFreezeDayUpsert)) *PackageFreezeDayUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackageFreezeDayUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageFreezeDayUpsertOne) SetUpdatedAt(v time.Time) *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertOne) UpdateUpdatedAt() *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDay sets the "day" field.
func (u *PackageFreezeDayUpsertOne) SetDay(v time.Time) *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetDay(v)
	})
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertOne) UpdateDay() *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateDay()
	})
}

// SetName sets the "name" field.
func (u *PackageFreezeDayUpsertOne) SetName(v string) *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertOne) UpdateName() *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *PackageFreezeDayUpsertOne) SetKind(v string) *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertOne) UpdateKind() *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateKind()
	})
}

// SetSource sets the "source" field.
func (u *PackageFreezeDayUpsertOne) SetSource(v string) *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertOne) UpdateSource() *PackageFreezeDayUpsertOne {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *PackageFreezeDayUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackageFreezeDayCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackageFreezeDayUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PackageFreezeDayUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PackageFreezeDayUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PackageFreezeDayCreateBulk is the builder for creating many PackageFreezeDay entities in bulk.
type PackageFreezeDayCreateBulk struct {
	config
	err      error
	builders []*PackageFreezeDayCreate
	conflict []sql.ConflictOption
}

// Save creates the PackageFreezeDay entities in the database.
func (_c *PackageFreezeDayCreateBulk) Save(ctx context.Context) ([]*PackageFreezeDay, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PackageFreezeDay, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageFreezeDayMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PackageFreezeDayCreateBulk) SaveX(ctx context.Context) []*PackageFreezeDay {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageFreezeDayCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageFreezeDayCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackageFreezeDay.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackageFreezeDayUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackageFreezeDayCreateBulk) OnConflict(opts ...sql.ConflictOption) *PackageFreezeDayUpsertBulk {
	_c.conflict = opts
	return &PackageFreezeDayUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackageFreezeDayCreateBulk) OnConflictColumns(columns ...string) *PackageFreezeDayUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackageFreezeDayUpsertBulk{
		create: _c,
	}
}

// PackageFreezeDayUpsertBulk is the builder for "upsert"-ing
// a bulk of PackageFreezeDay nodes.
type PackageFreezeDayUpsertBulk struct {
	create *PackageFreezeDayCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackageFreezeDayUpsertBulk) UpdateNewValues() *PackageFreezeDayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(packagefreezeday.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackageFreezeDay.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PackageFreezeDayUpsertBulk) Ignore() *PackageFreezeDayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackageFreezeDayUpsertBulk) DoNothing() *PackageFreezeDayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackageFreezeDayCreateBulk.OnConflict
// documentation for more info.
func (u *PackageFreezeDayUpsertBulk) Update(set func(*PackageFreezeDayUpsert)) *PackageFreezeDayUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackageFreezeDayUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageFreezeDayUpsertBulk) SetUpdatedAt(v time.Time) *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertBulk) UpdateUpdatedAt() *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDay sets the "day" field.
func (u *PackageFreezeDayUpsertBulk) SetDay(v time.Time) *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetDay(v)
	})
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertBulk) UpdateDay() *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateDay()
	})
}

// SetName sets the "name" field.
func (u *PackageFreezeDayUpsertBulk) SetName(v string) *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertBulk) UpdateName() *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateName()
	})
}

// SetKind sets the "kind" field.
func (u *PackageFreezeDayUpsertBulk) SetKind(v string) *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertBulk) UpdateKind() *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateKind()
	})
}

// SetSource sets the "source" field.
func (u *PackageFreezeDayUpsertBulk) SetSource(v string) *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *PackageFreezeDayUpsertBulk) UpdateSource() *PackageFreezeDayUpsertBulk {
	return u.Update(func(s *PackageFreezeDayUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *PackageFreezeDayUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PackageFreezeDayCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackageFreezeDayCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackageFreezeDayUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
