// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/packageplan"
)

// PackagePlanCreate is the builder for creating a PackagePlan entity.
type PackagePlanCreate struct {
	config
	mutation *PackagePlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PackagePlanCreate) SetCreatedAt(v time.Time) *PackagePlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PackagePlanCreate) SetNillableCreatedAt(v *time.Time) *PackagePlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PackagePlanCreate) SetUpdatedAt(v time.Time) *PackagePlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PackagePlanCreate) SetNillableUpdatedAt(v *time.Time) *PackagePlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PackagePlanCreate) SetGroupID(v int64) *PackagePlanCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PackagePlanCreate) SetName(v string) *PackagePlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCycle sets the "cycle" field.
func (_c *PackagePlanCreate) SetCycle(v string) *PackagePlanCreate {
	_c.mutation.SetCycle(v)
	return _c
}

// SetTier sets the "tier" field.
func (_c *PackagePlanCreate) SetTier(v int8) *PackagePlanCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *PackagePlanCreate) SetPrice(v float64) *PackagePlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetQuotaUsd sets the "quota_usd" field.
func (_c *PackagePlanCreate) SetQuotaUsd(v float64) *PackagePlanCreate {
	_c.mutation.SetQuotaUsd(v)
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *PackagePlanCreate) SetValidityDays(v int) *PackagePlanCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetForSale sets the "for_sale" field.
func (_c *PackagePlanCreate) SetForSale(v bool) *PackagePlanCreate {
	_c.mutation.SetForSale(v)
	return _c
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_c *PackagePlanCreate) SetNillableForSale(v *bool) *PackagePlanCreate {
	if v != nil {
		_c.SetForSale(*v)
	}
	return _c
}

// Mutation returns the PackagePlanMutation object of the builder.
func (_c *PackagePlanCreate) Mutation() *PackagePlanMutation {
	return _c.mutation
}

// Save creates the PackagePlan in the database.
func (_c *PackagePlanCreate) Save(ctx context.Context) (*PackagePlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PackagePlanCreate) SaveX(ctx context.Context) *PackagePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackagePlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackagePlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PackagePlanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := packageplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := packageplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		v := packageplan.DefaultForSale
		_c.mutation.SetForSale(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PackagePlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PackagePlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PackagePlan.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "PackagePlan.group_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PackagePlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := packageplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cycle(); !ok {
		return &ValidationError{Name: "cycle", err: errors.New(`ent: missing required field "PackagePlan.cycle"`)}
	}
	if v, ok := _c.mutation.Cycle(); ok {
		if err := packageplan.CycleValidator(v); err != nil {
			return &ValidationError{Name: "cycle", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "PackagePlan.tier"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "PackagePlan.price"`)}
	}
	if _, ok := _c.mutation.QuotaUsd(); !ok {
		return &ValidationError{Name: "quota_usd", err: errors.New(`ent: missing required field "PackagePlan.quota_usd"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "PackagePlan.validity_days"`)}
	}
	if _, ok := _c.mutation.ForSale(); !ok {
		return &ValidationError{Name: "for_sale", err: errors.New(`ent: missing required field "PackagePlan.for_sale"`)}
	}
	return nil
}

func (_c *PackagePlanCreate) sqlSave(ctx context.Context) (*PackagePlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PackagePlanCreate) createSpec() (*PackagePlan, *sqlgraph.CreateSpec) {
	var (
		_node = &PackagePlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(packageplan.Table, sqlgraph.NewFieldSpec(packageplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(packageplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(packageplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(packageplan.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(packageplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Cycle(); ok {
		_spec.SetField(packageplan.FieldCycle, field.TypeString, value)
		_node.Cycle = value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(packageplan.FieldTier, field.TypeInt8, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(packageplan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.QuotaUsd(); ok {
		_spec.SetField(packageplan.FieldQuotaUsd, field.TypeFloat64, value)
		_node.QuotaUsd = value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(packageplan.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.ForSale(); ok {
		_spec.SetField(packageplan.FieldForSale, field.TypeBool, value)
		_node.ForSale = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackagePlan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackagePlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackagePlanCreate) OnConflict(opts ...sql.ConflictOption) *PackagePlanUpsertOne {
	_c.conflict = opts
	return &PackagePlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackagePlanCreate) OnConflictColumns(columns ...string) *PackagePlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackagePlanUpsertOne{
		create: _c,
	}
}

type (
	// PackagePlanUpsertOne is the builder for "upsert"-ing
	//  one PackagePlan node.
	PackagePlanUpsertOne struct {
		create *PackagePlanCreate
	}

	// PackagePlanUpsert is the "OnConflict" setter.
	PackagePlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PackagePlanUpsert) SetUpdatedAt(v time.Time) *PackagePlanUpsert {
	u.Set(packageplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateUpdatedAt() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PackagePlanUpsert) SetGroupID(v int64) *PackagePlanUpsert {
	u.Set(packageplan.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateGroupID() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *PackagePlanUpsert) AddGroupID(v int64) *PackagePlanUpsert {
	u.Add(packageplan.FieldGroupID, v)
	return u
}

// SetName sets the "name" field.
func (u *PackagePlanUpsert) SetName(v string) *PackagePlanUpsert {
	u.Set(packageplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateName() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldName)
	return u
}

// SetCycle sets the "cycle" field.
func (u *PackagePlanUpsert) SetCycle(v string) *PackagePlanUpsert {
	u.Set(packageplan.FieldCycle, v)
	return u
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateCycle() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldCycle)
	return u
}

// SetTier sets the "tier" field.
func (u *PackagePlanUpsert) SetTier(v int8) *PackagePlanUpsert {
	u.Set(packageplan.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateTier() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldTier)
	return u
}

// AddTier adds v to the "tier" field.
func (u *PackagePlanUpsert) AddTier(v int8) *PackagePlanUpsert {
	u.Add(packageplan.FieldTier, v)
	return u
}

// SetPrice sets the "price" field.
func (u *PackagePlanUpsert) SetPrice(v float64) *PackagePlanUpsert {
	u.Set(packageplan.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdatePrice() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldPrice)
	return u
}

// AddPrice adds v to the "price" field.
func (u *PackagePlanUpsert) AddPrice(v float64) *PackagePlanUpsert {
	u.Add(packageplan.FieldPrice, v)
	return u
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *PackagePlanUpsert) SetQuotaUsd(v float64) *PackagePlanUpsert {
	u.Set(packageplan.FieldQuotaUsd, v)
	return u
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateQuotaUsd() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldQuotaUsd)
	return u
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *PackagePlanUpsert) AddQuotaUsd(v float64) *PackagePlanUpsert {
	u.Add(packageplan.FieldQuotaUsd, v)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *PackagePlanUpsert) SetValidityDays(v int) *PackagePlanUpsert {
	u.Set(packageplan.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateValidityDays() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PackagePlanUpsert) AddValidityDays(v int) *PackagePlanUpsert {
	u.Add(packageplan.FieldValidityDays, v)
	return u
}

// SetForSale sets the "for_sale" field.
func (u *PackagePlanUpsert) SetForSale(v bool) *PackagePlanUpsert {
	u.Set(packageplan.FieldForSale, v)
	return u
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *PackagePlanUpsert) UpdateForSale() *PackagePlanUpsert {
	u.SetExcluded(packageplan.FieldForSale)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackagePlanUpsertOne) UpdateNewValues() *PackagePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(packageplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PackagePlanUpsertOne) Ignore() *PackagePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackagePlanUpsertOne) DoNothing() *PackagePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackagePlanCreate.OnConflict
// documentation for more info.
func (u *PackagePlanUpsertOne) Update(set func(*PackagePlanUpsert)) *PackagePlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackagePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackagePlanUpsertOne) SetUpdatedAt(v time.Time) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateUpdatedAt() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PackagePlanUpsertOne) SetGroupID(v int64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PackagePlanUpsertOne) AddGroupID(v int64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateGroupID() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateGroupID()
	})
}

// SetName sets the "name" field.
func (u *PackagePlanUpsertOne) SetName(v string) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateName() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateName()
	})
}

// SetCycle sets the "cycle" field.
func (u *PackagePlanUpsertOne) SetCycle(v string) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetCycle(v)
	})
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateCycle() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateCycle()
	})
}

// SetTier sets the "tier" field.
func (u *PackagePlanUpsertOne) SetTier(v int8) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *PackagePlanUpsertOne) AddTier(v int8) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateTier() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateTier()
	})
}

// SetPrice sets the "price" field.
func (u *PackagePlanUpsertOne) SetPrice(v float64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PackagePlanUpsertOne) AddPrice(v float64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdatePrice() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdatePrice()
	})
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *PackagePlanUpsertOne) SetQuotaUsd(v float64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetQuotaUsd(v)
	})
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *PackagePlanUpsertOne) AddQuotaUsd(v float64) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddQuotaUsd(v)
	})
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateQuotaUsd() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateQuotaUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PackagePlanUpsertOne) SetValidityDays(v int) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PackagePlanUpsertOne) AddValidityDays(v int) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateValidityDays() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetForSale sets the "for_sale" field.
func (u *PackagePlanUpsertOne) SetForSale(v bool) *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *PackagePlanUpsertOne) UpdateForSale() *PackagePlanUpsertOne {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateForSale()
	})
}

// Exec executes the query.
func (u *PackagePlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackagePlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackagePlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PackagePlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PackagePlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PackagePlanCreateBulk is the builder for creating many PackagePlan entities in bulk.
type PackagePlanCreateBulk struct {
	config
	err      error
	builders []*PackagePlanCreate
	conflict []sql.ConflictOption
}

// Save creates the PackagePlan entities in the database.
func (_c *PackagePlanCreateBulk) Save(ctx context.Context) ([]*PackagePlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PackagePlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackagePlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PackagePlanCreateBulk) SaveX(ctx context.Context) []*PackagePlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackagePlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackagePlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackagePlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackagePlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackagePlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PackagePlanUpsertBulk {
	_c.conflict = opts
	return &PackagePlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackagePlanCreateBulk) OnConflictColumns(columns ...string) *PackagePlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackagePlanUpsertBulk{
		create: _c,
	}
}

// PackagePlanUpsertBulk is the builder for "upsert"-ing
// a bulk of PackagePlan nodes.
type PackagePlanUpsertBulk struct {
	create *PackagePlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackagePlanUpsertBulk) UpdateNewValues() *PackagePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(packageplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackagePlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PackagePlanUpsertBulk) Ignore() *PackagePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackagePlanUpsertBulk) DoNothing() *PackagePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackagePlanCreateBulk.OnConflict
// documentation for more info.
func (u *PackagePlanUpsertBulk) Update(set func(*PackagePlanUpsert)) *PackagePlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackagePlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackagePlanUpsertBulk) SetUpdatedAt(v time.Time) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateUpdatedAt() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PackagePlanUpsertBulk) SetGroupID(v int64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PackagePlanUpsertBulk) AddGroupID(v int64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateGroupID() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateGroupID()
	})
}

// SetName sets the "name" field.
func (u *PackagePlanUpsertBulk) SetName(v string) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateName() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateName()
	})
}

// SetCycle sets the "cycle" field.
func (u *PackagePlanUpsertBulk) SetCycle(v string) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetCycle(v)
	})
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateCycle() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateCycle()
	})
}

// SetTier sets the "tier" field.
func (u *PackagePlanUpsertBulk) SetTier(v int8) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *PackagePlanUpsertBulk) AddTier(v int8) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateTier() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateTier()
	})
}

// SetPrice sets the "price" field.
func (u *PackagePlanUpsertBulk) SetPrice(v float64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetPrice(v)
	})
}

// AddPrice adds v to the "price" field.
func (u *PackagePlanUpsertBulk) AddPrice(v float64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdatePrice() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdatePrice()
	})
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *PackagePlanUpsertBulk) SetQuotaUsd(v float64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetQuotaUsd(v)
	})
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *PackagePlanUpsertBulk) AddQuotaUsd(v float64) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddQuotaUsd(v)
	})
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateQuotaUsd() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateQuotaUsd()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *PackagePlanUpsertBulk) SetValidityDays(v int) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *PackagePlanUpsertBulk) AddValidityDays(v int) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateValidityDays() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateValidityDays()
	})
}

// SetForSale sets the "for_sale" field.
func (u *PackagePlanUpsertBulk) SetForSale(v bool) *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.SetForSale(v)
	})
}

// UpdateForSale sets the "for_sale" field to the value that was provided on create.
func (u *PackagePlanUpsertBulk) UpdateForSale() *PackagePlanUpsertBulk {
	return u.Update(func(s *PackagePlanUpsert) {
		s.UpdateForSale()
	})
}

// Exec executes the query.
func (u *PackagePlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PackagePlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackagePlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackagePlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
