// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/packageplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PackagePlanUpdate is the builder for updating PackagePlan entities.
type PackagePlanUpdate struct {
	config
	hooks    []Hook
	mutation *PackagePlanMutation
}

// Where appends a list predicates to the PackagePlanUpdate builder.
func (_u *PackagePlanUpdate) Where(ps ...predicate.PackagePlan) *PackagePlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PackagePlanUpdate) SetUpdatedAt(v time.Time) *PackagePlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PackagePlanUpdate) SetGroupID(v int64) *PackagePlanUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableGroupID(v *int64) *PackagePlanUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PackagePlanUpdate) AddGroupID(v int64) *PackagePlanUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PackagePlanUpdate) SetName(v string) *PackagePlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableName(v *string) *PackagePlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCycle sets the "cycle" field.
func (_u *PackagePlanUpdate) SetCycle(v string) *PackagePlanUpdate {
	_u.mutation.SetCycle(v)
	return _u
}

// SetNillableCycle sets the "cycle" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableCycle(v *string) *PackagePlanUpdate {
	if v != nil {
		_u.SetCycle(*v)
	}
	return _u
}

// SetTier sets the "tier" field.
func (_u *PackagePlanUpdate) SetTier(v int8) *PackagePlanUpdate {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableTier(v *int8) *PackagePlanUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *PackagePlanUpdate) AddTier(v int8) *PackagePlanUpdate {
	_u.mutation.AddTier(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PackagePlanUpdate) SetPrice(v float64) *PackagePlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillablePrice(v *float64) *PackagePlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PackagePlanUpdate) AddPrice(v float64) *PackagePlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetQuotaUsd sets the "quota_usd" field.
func (_u *PackagePlanUpdate) SetQuotaUsd(v float64) *PackagePlanUpdate {
	_u.mutation.ResetQuotaUsd()
	_u.mutation.SetQuotaUsd(v)
	return _u
}

// SetNillableQuotaUsd sets the "quota_usd" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableQuotaUsd(v *float64) *PackagePlanUpdate {
	if v != nil {
		_u.SetQuotaUsd(*v)
	}
	return _u
}

// AddQuotaUsd adds value to the "quota_usd" field.
func (_u *PackagePlanUpdate) AddQuotaUsd(v float64) *PackagePlanUpdate {
	_u.mutation.AddQuotaUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PackagePlanUpdate) SetValidityDays(v int) *PackagePlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableValidityDays(v *int) *PackagePlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PackagePlanUpdate) AddValidityDays(v int) *PackagePlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *PackagePlanUpdate) SetForSale(v bool) *PackagePlanUpdate {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *PackagePlanUpdate) SetNillableForSale(v *bool) *PackagePlanUpdate {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// Mutation returns the PackagePlanMutation object of the builder.
func (_u *PackagePlanUpdate) Mutation() *PackagePlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PackagePlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackagePlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PackagePlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackagePlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PackagePlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := packageplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PackagePlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := packageplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cycle(); ok {
		if err := packageplan.CycleValidator(v); err != nil {
			return &ValidationError{Name: "cycle", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.cycle": %w`, err)}
		}
	}
	return nil
}

func (_u *PackagePlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(packageplan.Table, packageplan.Columns, sqlgraph.NewFieldSpec(packageplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(packageplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(packageplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(packageplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(packageplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cycle(); ok {
		_spec.SetField(packageplan.FieldCycle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(packageplan.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(packageplan.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(packageplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(packageplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsd(); ok {
		_spec.SetField(packageplan.FieldQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsd(); ok {
		_spec.AddField(packageplan.FieldQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(packageplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(packageplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(packageplan.FieldForSale, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PackagePlanUpdateOne is the builder for updating a single PackagePlan entity.
type PackagePlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PackagePlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PackagePlanUpdateOne) SetUpdatedAt(v time.Time) *PackagePlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PackagePlanUpdateOne) SetGroupID(v int64) *PackagePlanUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableGroupID(v *int64) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *PackagePlanUpdateOne) AddGroupID(v int64) *PackagePlanUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PackagePlanUpdateOne) SetName(v string) *PackagePlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableName(v *string) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCycle sets the "cycle" field.
func (_u *PackagePlanUpdateOne) SetCycle(v string) *PackagePlanUpdateOne {
	_u.mutation.SetCycle(v)
	return _u
}

// SetNillableCycle sets the "cycle" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableCycle(v *string) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetCycle(*v)
	}
	return _u
}

// SetTier sets the "tier" field.
func (_u *PackagePlanUpdateOne) SetTier(v int8) *PackagePlanUpdateOne {
	_u.mutation.ResetTier()
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableTier(v *int8) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// AddTier adds value to the "tier" field.
func (_u *PackagePlanUpdateOne) AddTier(v int8) *PackagePlanUpdateOne {
	_u.mutation.AddTier(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PackagePlanUpdateOne) SetPrice(v float64) *PackagePlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillablePrice(v *float64) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PackagePlanUpdateOne) AddPrice(v float64) *PackagePlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetQuotaUsd sets the "quota_usd" field.
func (_u *PackagePlanUpdateOne) SetQuotaUsd(v float64) *PackagePlanUpdateOne {
	_u.mutation.ResetQuotaUsd()
	_u.mutation.SetQuotaUsd(v)
	return _u
}

// SetNillableQuotaUsd sets the "quota_usd" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableQuotaUsd(v *float64) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetQuotaUsd(*v)
	}
	return _u
}

// AddQuotaUsd adds value to the "quota_usd" field.
func (_u *PackagePlanUpdateOne) AddQuotaUsd(v float64) *PackagePlanUpdateOne {
	_u.mutation.AddQuotaUsd(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *PackagePlanUpdateOne) SetValidityDays(v int) *PackagePlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableValidityDays(v *int) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *PackagePlanUpdateOne) AddValidityDays(v int) *PackagePlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetForSale sets the "for_sale" field.
func (_u *PackagePlanUpdateOne) SetForSale(v bool) *PackagePlanUpdateOne {
	_u.mutation.SetForSale(v)
	return _u
}

// SetNillableForSale sets the "for_sale" field if the given value is not nil.
func (_u *PackagePlanUpdateOne) SetNillableForSale(v *bool) *PackagePlanUpdateOne {
	if v != nil {
		_u.SetForSale(*v)
	}
	return _u
}

// Mutation returns the PackagePlanMutation object of the builder.
func (_u *PackagePlanUpdateOne) Mutation() *PackagePlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the PackagePlanUpdate builder.
func (_u *PackagePlanUpdateOne) Where(ps ...predicate.PackagePlan) *PackagePlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PackagePlanUpdateOne) Select(field string, fields ...string) *PackagePlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PackagePlan entity.
func (_u *PackagePlanUpdateOne) Save(ctx context.Context) (*PackagePlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackagePlanUpdateOne) SaveX(ctx context.Context) *PackagePlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PackagePlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackagePlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PackagePlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := packageplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PackagePlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := packageplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cycle(); ok {
		if err := packageplan.CycleValidator(v); err != nil {
			return &ValidationError{Name: "cycle", err: fmt.Errorf(`ent: validator failed for field "PackagePlan.cycle": %w`, err)}
		}
	}
	return nil
}

func (_u *PackagePlanUpdateOne) sqlSave(ctx context.Context) (_node *PackagePlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(packageplan.Table, packageplan.Columns, sqlgraph.NewFieldSpec(packageplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PackagePlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, packageplan.FieldID)
		for _, f := range fields {
			if !packageplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != packageplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(packageplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(packageplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(packageplan.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(packageplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cycle(); ok {
		_spec.SetField(packageplan.FieldCycle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(packageplan.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedTier(); ok {
		_spec.AddField(packageplan.FieldTier, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(packageplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(packageplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsd(); ok {
		_spec.SetField(packageplan.FieldQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsd(); ok {
		_spec.AddField(packageplan.FieldQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(packageplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(packageplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ForSale(); ok {
		_spec.SetField(packageplan.FieldForSale, field.TypeBool, value)
	}
	_node = &PackagePlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
