// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/userpackagefreeze"
)

// UserPackageFreezeCreate is the builder for creating a UserPackageFreeze entity.
type UserPackageFreezeCreate struct {
	config
	mutation *UserPackageFreezeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPackageFreezeCreate) SetCreatedAt(v time.Time) *UserPackageFreezeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPackageFreezeCreate) SetNillableCreatedAt(v *time.Time) *UserPackageFreezeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPackageFreezeCreate) SetUpdatedAt(v time.Time) *UserPackageFreezeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPackageFreezeCreate) SetNillableUpdatedAt(v *time.Time) *UserPackageFreezeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *UserPackageFreezeCreate) SetPackageID(v int64) *UserPackageFreezeCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserPackageFreezeCreate) SetUserID(v int64) *UserPackageFreezeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFrozenAt sets the "frozen_at" field.
func (_c *UserPackageFreezeCreate) SetFrozenAt(v time.Time) *UserPackageFreezeCreate {
	_c.mutation.SetFrozenAt(v)
	return _c
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (_c *UserPackageFreezeCreate) SetUnfrozenAt(v time.Time) *UserPackageFreezeCreate {
	_c.mutation.SetUnfrozenAt(v)
	return _c
}

// SetNillableUnfrozenAt sets the "unfrozen_at" field if the given value is not nil.
func (_c *UserPackageFreezeCreate) SetNillableUnfrozenAt(v *time.Time) *UserPackageFreezeCreate {
	if v != nil {
		_c.SetUnfrozenAt(*v)
	}
	return _c
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (_c *UserPackageFreezeCreate) SetUnfreezeReason(v string) *UserPackageFreezeCreate {
	_c.mutation.SetUnfreezeReason(v)
	return _c
}

// SetNillableUnfreezeReason sets the "unfreeze_reason" field if the given value is not nil.
func (_c *UserPackageFreezeCreate) SetNillableUnfreezeReason(v *string) *UserPackageFreezeCreate {
	if v != nil {
		_c.SetUnfreezeReason(*v)
	}
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *UserPackageFreezeCreate) SetDurationSeconds(v int64) *UserPackageFreezeCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *UserPackageFreezeCreate) SetNillableDurationSeconds(v *int64) *UserPackageFreezeCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// Mutation returns the UserPackageFreezeMutation object of the builder.
func (_c *UserPackageFreezeCreate) Mutation() *UserPackageFreezeMutation {
	return _c.mutation
}

// Save creates the UserPackageFreeze in the database.
func (_c *UserPackageFreezeCreate) Save(ctx context.Context) (*UserPackageFreeze, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPackageFreezeCreate) SaveX(ctx context.Context) *UserPackageFreeze {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPackageFreezeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPackageFreezeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPackageFreezeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userpackagefreeze.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userpackagefreeze.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UnfreezeReason(); !ok {
		v := userpackagefreeze.DefaultUnfreezeReason
		_c.mutation.SetUnfreezeReason(v)
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		v := userpackagefreeze.DefaultDurationSeconds
		_c.mutation.SetDurationSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPackageFreezeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPackageFreeze.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPackageFreeze.updated_at"`)}
	}
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "UserPackageFreeze.package_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPackageFreeze.user_id"`)}
	}
	if _, ok := _c.mutation.FrozenAt(); !ok {
		return &ValidationError{Name: "frozen_at", err: errors.New(`ent: missing required field "UserPackageFreeze.frozen_at"`)}
	}
	if _, ok := _c.mutation.UnfreezeReason(); !ok {
		return &ValidationError{Name: "unfreeze_reason", err: errors.New(`ent: missing required field "UserPackageFreeze.unfreeze_reason"`)}
	}
	if v, ok := _c.mutation.UnfreezeReason(); ok {
		if err := userpackagefreeze.UnfreezeReasonValidator(v); err != nil {
			return &ValidationError{Name: "unfreeze_reason", err: fmt.Errorf(`ent: validator failed for field "UserPackageFreeze.unfreeze_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "UserPackageFreeze.duration_seconds"`)}
	}
	return nil
}

func (_c *UserPackageFreezeCreate) sqlSave(ctx context.Context) (*UserPackageFreeze, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPackageFreezeCreate) createSpec() (*UserPackageFreeze, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPackageFreeze{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpackagefreeze.Table, sqlgraph.NewFieldSpec(userpackagefreeze.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpackagefreeze.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(userpackagefreeze.FieldPackageID, field.TypeInt64, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userpackagefreeze.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.FrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldFrozenAt, field.TypeTime, value)
		_node.FrozenAt = value
	}
	if value, ok := _c.mutation.UnfrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfrozenAt, field.TypeTime, value)
		_node.UnfrozenAt = &value
	}
	if value, ok := _c.mutation.UnfreezeReason(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfreezeReason, field.TypeString, value)
		_node.UnfreezeReason = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(userpackagefreeze.FieldDurationSeconds, field.TypeInt64, value)
		_node.DurationSeconds = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPackageFreeze.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPackageFreezeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPackageFreezeCreate) OnConflict(opts ...sql.ConflictOption) *UserPackageFreezeUpsertOne {
	_c.conflict = opts
	return &UserPackageFreezeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPackageFreezeCreate) OnConflictColumns(columns ...string) *UserPackageFreezeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPackageFreezeUpsertOne{
		create: _c,
	}
}

type (
	// UserPackageFreezeUpsertOne is the builder for "upsert"-ing
	//  one UserPackageFreeze node.
	UserPackageFreezeUpsertOne struct {
		create *UserPackageFreezeCreate
	}

	// UserPackageFreezeUpsert is the "OnConflict" setter.
	UserPackageFreezeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageFreezeUpsert) SetUpdatedAt(v time.Time) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateUpdatedAt() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldUpdatedAt)
	return u
}

// SetPackageID sets the "package_id" field.
func (u *UserPackageFreezeUpsert) SetPackageID(v int64) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldPackageID, v)
	return u
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdatePackageID() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldPackageID)
	return u
}

// AddPackageID adds v to the "package_id" field.
func (u *UserPackageFreezeUpsert) AddPackageID(v int64) *UserPackageFreezeUpsert {
	u.Add(userpackagefreeze.FieldPackageID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserPackageFreezeUpsert) SetUserID(v int64) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateUserID() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageFreezeUpsert) AddUserID(v int64) *UserPackageFreezeUpsert {
	u.Add(userpackagefreeze.FieldUserID, v)
	return u
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageFreezeUpsert) SetFrozenAt(v time.Time) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldFrozenAt, v)
	return u
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateFrozenAt() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldFrozenAt)
	return u
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (u *UserPackageFreezeUpsert) SetUnfrozenAt(v time.Time) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldUnfrozenAt, v)
	return u
}

// UpdateUnfrozenAt sets the "unfrozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateUnfrozenAt() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldUnfrozenAt)
	return u
}

// ClearUnfrozenAt clears the value of the "unfrozen_at" field.
func (u *UserPackageFreezeUpsert) ClearUnfrozenAt() *UserPackageFreezeUpsert {
	u.SetNull(userpackagefreeze.FieldUnfrozenAt)
	return u
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (u *UserPackageFreezeUpsert) SetUnfreezeReason(v string) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldUnfreezeReason, v)
	return u
}

// UpdateUnfreezeReason sets the "unfreeze_reason" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateUnfreezeReason() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldUnfreezeReason)
	return u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *UserPackageFreezeUpsert) SetDurationSeconds(v int64) *UserPackageFreezeUpsert {
	u.Set(userpackagefreeze.FieldDurationSeconds, v)
	return u
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *UserPackageFreezeUpsert) UpdateDurationSeconds() *UserPackageFreezeUpsert {
	u.SetExcluded(userpackagefreeze.FieldDurationSeconds)
	return u
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *UserPackageFreezeUpsert) AddDurationSeconds(v int64) *UserPackageFreezeUpsert {
	u.Add(userpackagefreeze.FieldDurationSeconds, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPackageFreezeUpsertOne) UpdateNewValues() *UserPackageFreezeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userpackagefreeze.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserPackageFreezeUpsertOne) Ignore() *UserPackageFreezeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPackageFreezeUpsertOne) DoNothing() *UserPackageFreezeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPackageFreezeCreate.OnConflict
// documentation for more info.
func (u *UserPackageFreezeUpsertOne) Update(set func(*UserPackageFreezeUpsert)) *UserPackageFreezeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPackageFreezeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageFreezeUpsertOne) SetUpdatedAt(v time.Time) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateUpdatedAt() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPackageID sets the "package_id" field.
func (u *UserPackageFreezeUpsertOne) SetPackageID(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *UserPackageFreezeUpsertOne) AddPackageID(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdatePackageID() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdatePackageID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserPackageFreezeUpsertOne) SetUserID(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageFreezeUpsertOne) AddUserID(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateUserID() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUserID()
	})
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageFreezeUpsertOne) SetFrozenAt(v time.Time) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetFrozenAt(v)
	})
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateFrozenAt() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateFrozenAt()
	})
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (u *UserPackageFreezeUpsertOne) SetUnfrozenAt(v time.Time) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUnfrozenAt(v)
	})
}

// UpdateUnfrozenAt sets the "unfrozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateUnfrozenAt() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUnfrozenAt()
	})
}

// ClearUnfrozenAt clears the value of the "unfrozen_at" field.
func (u *UserPackageFreezeUpsertOne) ClearUnfrozenAt() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.ClearUnfrozenAt()
	})
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (u *UserPackageFreezeUpsertOne) SetUnfreezeReason(v string) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUnfreezeReason(v)
	})
}

// UpdateUnfreezeReason sets the "unfreeze_reason" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateUnfreezeReason() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUnfreezeReason()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *UserPackageFreezeUpsertOne) SetDurationSeconds(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *UserPackageFreezeUpsertOne) AddDurationSeconds(v int64) *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertOne) UpdateDurationSeconds() *UserPackageFreezeUpsertOne {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateDurationSeconds()
	})
}

// Exec executes the query.
func (u *UserPackageFreezeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPackageFreezeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPackageFreezeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserPackageFreezeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserPackageFreezeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserPackageFreezeCreateBulk is the builder for creating many UserPackageFreeze entities in bulk.
type UserPackageFreezeCreateBulk struct {
	config
	err      error
	builders []*UserPackageFreezeCreate
	conflict []sql.ConflictOption
}

// Save creates the UserPackageFreeze entities in the database.
func (_c *UserPackageFreezeCreateBulk) Save(ctx context.Context) ([]*UserPackageFreeze, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPackageFreeze, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPackageFreezeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPackageFreezeCreateBulk) SaveX(ctx context.Context) []*UserPackageFreeze {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPackageFreezeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPackageFreezeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPackageFreeze.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPackageFreezeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPackageFreezeCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserPackageFreezeUpsertBulk {
	_c.conflict = opts
	return &UserPackageFreezeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPackageFreezeCreateBulk) OnConflictColumns(columns ...string) *UserPackageFreezeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPackageFreezeUpsertBulk{
		create: _c,
	}
}

// UserPackageFreezeUpsertBulk is the builder for "upsert"-ing
// a bulk of UserPackageFreeze nodes.
type UserPackageFreezeUpsertBulk struct {
	create *UserPackageFreezeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPackageFreezeUpsertBulk) UpdateNewValues() *UserPackageFreezeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userpackagefreeze.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPackageFreeze.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserPackageFreezeUpsertBulk) Ignore() *UserPackageFreezeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPackageFreezeUpsertBulk) DoNothing() *UserPackageFreezeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPackageFreezeCreateBulk.OnConflict
// documentation for more info.
func (u *UserPackageFreezeUpsertBulk) Update(set func(*UserPackageFreezeUpsert)) *UserPackageFreezeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPackageFreezeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageFreezeUpsertBulk) SetUpdatedAt(v time.Time) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateUpdatedAt() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPackageID sets the "package_id" field.
func (u *UserPackageFreezeUpsertBulk) SetPackageID(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetPackageID(v)
	})
}

// AddPackageID adds v to the "package_id" field.
func (u *UserPackageFreezeUpsertBulk) AddPackageID(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddPackageID(v)
	})
}

// UpdatePackageID sets the "package_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdatePackageID() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdatePackageID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserPackageFreezeUpsertBulk) SetUserID(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageFreezeUpsertBulk) AddUserID(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateUserID() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUserID()
	})
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageFreezeUpsertBulk) SetFrozenAt(v time.Time) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetFrozenAt(v)
	})
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateFrozenAt() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateFrozenAt()
	})
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (u *UserPackageFreezeUpsertBulk) SetUnfrozenAt(v time.Time) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUnfrozenAt(v)
	})
}

// UpdateUnfrozenAt sets the "unfrozen_at" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateUnfrozenAt() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUnfrozenAt()
	})
}

// ClearUnfrozenAt clears the value of the "unfrozen_at" field.
func (u *UserPackageFreezeUpsertBulk) ClearUnfrozenAt() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.ClearUnfrozenAt()
	})
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (u *UserPackageFreezeUpsertBulk) SetUnfreezeReason(v string) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetUnfreezeReason(v)
	})
}

// UpdateUnfreezeReason sets the "unfreeze_reason" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateUnfreezeReason() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateUnfreezeReason()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *UserPackageFreezeUpsertBulk) SetDurationSeconds(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *UserPackageFreezeUpsertBulk) AddDurationSeconds(v int64) *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *UserPackageFreezeUpsertBulk) UpdateDurationSeconds() *UserPackageFreezeUpsertBulk {
	return u.Update(func(s *UserPackageFreezeUpsert) {
		s.UpdateDurationSeconds()
	})
}

// Exec executes the query.
func (u *UserPackageFreezeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserPackageFreezeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPackageFreezeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPackageFreezeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
