// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/userpackagefreeze"
)

// UserPackageFreeze is the model entity for the UserPackageFreeze schema.
type UserPackageFreeze struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PackageID holds the value of the "package_id" field.
	PackageID int64 `json:"package_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// FrozenAt holds the value of the "frozen_at" field.
	FrozenAt time.Time `json:"frozen_at,omitempty"`
	// UnfrozenAt holds the value of the "unfrozen_at" field.
	UnfrozenAt *time.Time `json:"unfrozen_at,omitempty"`
	// UnfreezeReason holds the value of the "unfreeze_reason" field.
	UnfreezeReason string `json:"unfreeze_reason,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds int64 `json:"duration_seconds,omitempty"`
	selectValues    sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPackageFreeze) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpackagefreeze.FieldID, userpackagefreeze.FieldPackageID, userpackagefreeze.FieldUserID, userpackagefreeze.FieldDurationSeconds:
			values[i] = new(sql.NullInt64)
		case userpackagefreeze.FieldUnfreezeReason:
			values[i] = new(sql.NullString)
		case userpackagefreeze.FieldCreatedAt, userpackagefreeze.FieldUpdatedAt, userpackagefreeze.FieldFrozenAt, userpackagefreeze.FieldUnfrozenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPackageFreeze fields.
func (_m *UserPackageFreeze) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpackagefreeze.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userpackagefreeze.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userpackagefreeze.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case userpackagefreeze.FieldPackageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				_m.PackageID = value.Int64
			}
		case userpackagefreeze.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userpackagefreeze.FieldFrozenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field frozen_at", values[i])
			} else if value.Valid {
				_m.FrozenAt = value.Time
			}
		case userpackagefreeze.FieldUnfrozenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field unfrozen_at", values[i])
			} else if value.Valid {
				_m.UnfrozenAt = new(time.Time)
				*_m.UnfrozenAt = value.Time
			}
		case userpackagefreeze.FieldUnfreezeReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unfreeze_reason", values[i])
			} else if value.Valid {
				_m.UnfreezeReason = value.String
			}
		case userpackagefreeze.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPackageFreeze.
// This includes values selected through modifiers, order, etc.
func (_m *UserPackageFreeze) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserPackageFreeze.
// Note that you need to call UserPackageFreeze.Unwrap() before calling this method if this UserPackageFreeze
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPackageFreeze) Update() *UserPackageFreezeUpdateOne {
	return NewUserPackageFreezeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPackageFreeze entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPackageFreeze) Unwrap() *UserPackageFreeze {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPackageFreeze is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPackageFreeze) String() string {
	var builder strings.Builder
	builder.WriteString("UserPackageFreeze(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("package_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PackageID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("frozen_at=")
	builder.WriteString(_m.FrozenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UnfrozenAt; v != nil {
		builder.WriteString("unfrozen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("unfreeze_reason=")
	builder.WriteString(_m.UnfreezeReason)
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteByte(')')
	return builder.String()
}

// UserPackageFreezes is a parsable slice of UserPackageFreeze.
type UserPackageFreezes []*UserPackageFreeze
