// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/userpackage"
)

// UserPackageCreate is the builder for creating a UserPackage entity.
type UserPackageCreate struct {
	config
	mutation *UserPackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPackageCreate) SetCreatedAt(v time.Time) *UserPackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableCreatedAt(v *time.Time) *UserPackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPackageCreate) SetUpdatedAt(v time.Time) *UserPackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableUpdatedAt(v *time.Time) *UserPackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserPackageCreate) SetUserID(v int64) *UserPackageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserPackageCreate) SetGroupID(v int64) *UserPackageCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *UserPackageCreate) SetPlanID(v int64) *UserPackageCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *UserPackageCreate) SetOrderID(v int64) *UserPackageCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableOrderID(v *int64) *UserPackageCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UserPackageCreate) SetName(v string) *UserPackageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCycle sets the "cycle" field.
func (_c *UserPackageCreate) SetCycle(v string) *UserPackageCreate {
	_c.mutation.SetCycle(v)
	return _c
}

// SetTier sets the "tier" field.
func (_c *UserPackageCreate) SetTier(v int8) *UserPackageCreate {
	_c.mutation.SetTier(v)
	return _c
}

// SetQuotaUsd sets the "quota_usd" field.
func (_c *UserPackageCreate) SetQuotaUsd(v float64) *UserPackageCreate {
	_c.mutation.SetQuotaUsd(v)
	return _c
}

// SetUsedUsd sets the "used_usd" field.
func (_c *UserPackageCreate) SetUsedUsd(v float64) *UserPackageCreate {
	_c.mutation.SetUsedUsd(v)
	return _c
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableUsedUsd(v *float64) *UserPackageCreate {
	if v != nil {
		_c.SetUsedUsd(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserPackageCreate) SetStartsAt(v time.Time) *UserPackageCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserPackageCreate) SetExpiresAt(v time.Time) *UserPackageCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserPackageCreate) SetStatus(v string) *UserPackageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableStatus(v *string) *UserPackageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetFrozenAt sets the "frozen_at" field.
func (_c *UserPackageCreate) SetFrozenAt(v time.Time) *UserPackageCreate {
	_c.mutation.SetFrozenAt(v)
	return _c
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableFrozenAt(v *time.Time) *UserPackageCreate {
	if v != nil {
		_c.SetFrozenAt(*v)
	}
	return _c
}

// SetFrozenSecondsTotal sets the "frozen_seconds_total" field.
func (_c *UserPackageCreate) SetFrozenSecondsTotal(v int64) *UserPackageCreate {
	_c.mutation.SetFrozenSecondsTotal(v)
	return _c
}

// SetNillableFrozenSecondsTotal sets the "frozen_seconds_total" field if the given value is not nil.
func (_c *UserPackageCreate) SetNillableFrozenSecondsTotal(v *int64) *UserPackageCreate {
	if v != nil {
		_c.SetFrozenSecondsTotal(*v)
	}
	return _c
}

// Mutation returns the UserPackageMutation object of the builder.
func (_c *UserPackageCreate) Mutation() *UserPackageMutation {
	return _c.mutation
}

// Save creates the UserPackage in the database.
func (_c *UserPackageCreate) Save(ctx context.Context) (*UserPackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPackageCreate) SaveX(ctx context.Context) *UserPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPackageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userpackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userpackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		v := userpackage.DefaultUsedUsd
		_c.mutation.SetUsedUsd(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := userpackage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.FrozenSecondsTotal(); !ok {
		v := userpackage.DefaultFrozenSecondsTotal
		_c.mutation.SetFrozenSecondsTotal(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPackageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPackage.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPackage.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserPackage.group_id"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "UserPackage.plan_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UserPackage.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := userpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UserPackage.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cycle(); !ok {
		return &ValidationError{Name: "cycle", err: errors.New(`ent: missing required field "UserPackage.cycle"`)}
	}
	if v, ok := _c.mutation.Cycle(); ok {
		if err := userpackage.CycleValidator(v); err != nil {
			return &ValidationError{Name: "cycle", err: fmt.Errorf(`ent: validator failed for field "UserPackage.cycle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Tier(); !ok {
		return &ValidationError{Name: "tier", err: errors.New(`ent: missing required field "UserPackage.tier"`)}
	}
	if _, ok := _c.mutation.QuotaUsd(); !ok {
		return &ValidationError{Name: "quota_usd", err: errors.New(`ent: missing required field "UserPackage.quota_usd"`)}
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		return &ValidationError{Name: "used_usd", err: errors.New(`ent: missing required field "UserPackage.used_usd"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserPackage.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserPackage.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserPackage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := userpackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserPackage.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FrozenSecondsTotal(); !ok {
		return &ValidationError{Name: "frozen_seconds_total", err: errors.New(`ent: missing required field "UserPackage.frozen_seconds_total"`)}
	}
	return nil
}

func (_c *UserPackageCreate) sqlSave(ctx context.Context) (*UserPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPackageCreate) createSpec() (*UserPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpackage.Table, sqlgraph.NewFieldSpec(userpackage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userpackage.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(userpackage.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(userpackage.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(userpackage.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(userpackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Cycle(); ok {
		_spec.SetField(userpackage.FieldCycle, field.TypeString, value)
		_node.Cycle = value
	}
	if value, ok := _c.mutation.Tier(); ok {
		_spec.SetField(userpackage.FieldTier, field.TypeInt8, value)
		_node.Tier = value
	}
	if value, ok := _c.mutation.QuotaUsd(); ok {
		_spec.SetField(userpackage.FieldQuotaUsd, field.TypeFloat64, value)
		_node.QuotaUsd = value
	}
	if value, ok := _c.mutation.UsedUsd(); ok {
		_spec.SetField(userpackage.FieldUsedUsd, field.TypeFloat64, value)
		_node.UsedUsd = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(userpackage.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(userpackage.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(userpackage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.FrozenAt(); ok {
		_spec.SetField(userpackage.FieldFrozenAt, field.TypeTime, value)
		_node.FrozenAt = &value
	}
	if value, ok := _c.mutation.FrozenSecondsTotal(); ok {
		_spec.SetField(userpackage.FieldFrozenSecondsTotal, field.TypeInt64, value)
		_node.FrozenSecondsTotal = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPackage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPackageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPackageCreate) OnConflict(opts ...sql.ConflictOption) *UserPackageUpsertOne {
	_c.conflict = opts
	return &UserPackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPackageCreate) OnConflictColumns(columns ...string) *UserPackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPackageUpsertOne{
		create: _c,
	}
}

type (
	// UserPackageUpsertOne is the builder for "upsert"-ing
	//  one UserPackage node.
	UserPackageUpsertOne struct {
		create *UserPackageCreate
	}

	// UserPackageUpsert is the "OnConflict" setter.
	UserPackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageUpsert) SetUpdatedAt(v time.Time) *UserPackageUpsert {
	u.Set(userpackage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateUpdatedAt() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserPackageUpsert) SetUserID(v int64) *UserPackageUpsert {
	u.Set(userpackage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateUserID() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageUpsert) AddUserID(v int64) *UserPackageUpsert {
	u.Add(userpackage.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserPackageUpsert) SetGroupID(v int64) *UserPackageUpsert {
	u.Set(userpackage.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateGroupID() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *UserPackageUpsert) AddGroupID(v int64) *UserPackageUpsert {
	u.Add(userpackage.FieldGroupID, v)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UserPackageUpsert) SetPlanID(v int64) *UserPackageUpsert {
	u.Set(userpackage.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdatePlanID() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserPackageUpsert) AddPlanID(v int64) *UserPackageUpsert {
	u.Add(userpackage.FieldPlanID, v)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *UserPackageUpsert) SetOrderID(v int64) *UserPackageUpsert {
	u.Set(userpackage.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateOrderID() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *UserPackageUpsert) AddOrderID(v int64) *UserPackageUpsert {
	u.Add(userpackage.FieldOrderID, v)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserPackageUpsert) ClearOrderID() *UserPackageUpsert {
	u.SetNull(userpackage.FieldOrderID)
	return u
}

// SetName sets the "name" field.
func (u *UserPackageUpsert) SetName(v string) *UserPackageUpsert {
	u.Set(userpackage.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateName() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldName)
	return u
}

// SetCycle sets the "cycle" field.
func (u *UserPackageUpsert) SetCycle(v string) *UserPackageUpsert {
	u.Set(userpackage.FieldCycle, v)
	return u
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateCycle() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldCycle)
	return u
}

// SetTier sets the "tier" field.
func (u *UserPackageUpsert) SetTier(v int8) *UserPackageUpsert {
	u.Set(userpackage.FieldTier, v)
	return u
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateTier() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldTier)
	return u
}

// AddTier adds v to the "tier" field.
func (u *UserPackageUpsert) AddTier(v int8) *UserPackageUpsert {
	u.Add(userpackage.FieldTier, v)
	return u
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *UserPackageUpsert) SetQuotaUsd(v float64) *UserPackageUpsert {
	u.Set(userpackage.FieldQuotaUsd, v)
	return u
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateQuotaUsd() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldQuotaUsd)
	return u
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *UserPackageUpsert) AddQuotaUsd(v float64) *UserPackageUpsert {
	u.Add(userpackage.FieldQuotaUsd, v)
	return u
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserPackageUpsert) SetUsedUsd(v float64) *UserPackageUpsert {
	u.Set(userpackage.FieldUsedUsd, v)
	return u
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateUsedUsd() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldUsedUsd)
	return u
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserPackageUpsert) AddUsedUsd(v float64) *UserPackageUpsert {
	u.Add(userpackage.FieldUsedUsd, v)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserPackageUpsert) SetStartsAt(v time.Time) *UserPackageUpsert {
	u.Set(userpackage.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateStartsAt() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserPackageUpsert) SetExpiresAt(v time.Time) *UserPackageUpsert {
	u.Set(userpackage.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateExpiresAt() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserPackageUpsert) SetStatus(v string) *UserPackageUpsert {
	u.Set(userpackage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateStatus() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldStatus)
	return u
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageUpsert) SetFrozenAt(v time.Time) *UserPackageUpsert {
	u.Set(userpackage.FieldFrozenAt, v)
	return u
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateFrozenAt() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldFrozenAt)
	return u
}

// ClearFrozenAt clears the value of the "frozen_at" field.
func (u *UserPackageUpsert) ClearFrozenAt() *UserPackageUpsert {
	u.SetNull(userpackage.FieldFrozenAt)
	return u
}

// SetFrozenSecondsTotal sets the "frozen_seconds_total" field.
func (u *UserPackageUpsert) SetFrozenSecondsTotal(v int64) *UserPackageUpsert {
	u.Set(userpackage.FieldFrozenSecondsTotal, v)
	return u
}

// UpdateFrozenSecondsTotal sets the "frozen_seconds_total" field to the value that was provided on create.
func (u *UserPackageUpsert) UpdateFrozenSecondsTotal() *UserPackageUpsert {
	u.SetExcluded(userpackage.FieldFrozenSecondsTotal)
	return u
}

// AddFrozenSecondsTotal adds v to the "frozen_seconds_total" field.
func (u *UserPackageUpsert) AddFrozenSecondsTotal(v int64) *UserPackageUpsert {
	u.Add(userpackage.FieldFrozenSecondsTotal, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPackageUpsertOne) UpdateNewValues() *UserPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userpackage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserPackageUpsertOne) Ignore() *UserPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPackageUpsertOne) DoNothing() *UserPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPackageCreate.OnConflict
// documentation for more info.
func (u *UserPackageUpsertOne) Update(set func(*UserPackageUpsert)) *UserPackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageUpsertOne) SetUpdatedAt(v time.Time) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateUpdatedAt() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserPackageUpsertOne) SetUserID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageUpsertOne) AddUserID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateUserID() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserPackageUpsertOne) SetGroupID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserPackageUpsertOne) AddGroupID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateGroupID() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserPackageUpsertOne) SetPlanID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserPackageUpsertOne) AddPlanID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdatePlanID() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdatePlanID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserPackageUpsertOne) SetOrderID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *UserPackageUpsertOne) AddOrderID(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateOrderID() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserPackageUpsertOne) ClearOrderID() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.ClearOrderID()
	})
}

// SetName sets the "name" field.
func (u *UserPackageUpsertOne) SetName(v string) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateName() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateName()
	})
}

// SetCycle sets the "cycle" field.
func (u *UserPackageUpsertOne) SetCycle(v string) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetCycle(v)
	})
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateCycle() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateCycle()
	})
}

// SetTier sets the "tier" field.
func (u *UserPackageUpsertOne) SetTier(v int8) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *UserPackageUpsertOne) AddTier(v int8) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateTier() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateTier()
	})
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *UserPackageUpsertOne) SetQuotaUsd(v float64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetQuotaUsd(v)
	})
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *UserPackageUpsertOne) AddQuotaUsd(v float64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddQuotaUsd(v)
	})
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateQuotaUsd() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateQuotaUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserPackageUpsertOne) SetUsedUsd(v float64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserPackageUpsertOne) AddUsedUsd(v float64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateUsedUsd() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserPackageUpsertOne) SetStartsAt(v time.Time) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateStartsAt() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserPackageUpsertOne) SetExpiresAt(v time.Time) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateExpiresAt() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserPackageUpsertOne) SetStatus(v string) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateStatus() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateStatus()
	})
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageUpsertOne) SetFrozenAt(v time.Time) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetFrozenAt(v)
	})
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateFrozenAt() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateFrozenAt()
	})
}

// ClearFrozenAt clears the value of the "frozen_at" field.
func (u *UserPackageUpsertOne) ClearFrozenAt() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.ClearFrozenAt()
	})
}

// SetFrozenSecondsTotal sets the "frozen_seconds_total" field.
func (u *UserPackageUpsertOne) SetFrozenSecondsTotal(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetFrozenSecondsTotal(v)
	})
}

// AddFrozenSecondsTotal adds v to the "frozen_seconds_total" field.
func (u *UserPackageUpsertOne) AddFrozenSecondsTotal(v int64) *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddFrozenSecondsTotal(v)
	})
}

// UpdateFrozenSecondsTotal sets the "frozen_seconds_total" field to the value that was provided on create.
func (u *UserPackageUpsertOne) UpdateFrozenSecondsTotal() *UserPackageUpsertOne {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateFrozenSecondsTotal()
	})
}

// Exec executes the query.
func (u *UserPackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserPackageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserPackageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserPackageCreateBulk is the builder for creating many UserPackage entities in bulk.
type UserPackageCreateBulk struct {
	config
	err      error
	builders []*UserPackageCreate
	conflict []sql.ConflictOption
}

// Save creates the UserPackage entities in the database.
func (_c *UserPackageCreateBulk) Save(ctx context.Context) ([]*UserPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPackageCreateBulk) SaveX(ctx context.Context) []*UserPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserPackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserPackageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserPackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserPackageUpsertBulk {
	_c.conflict = opts
	return &UserPackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserPackageCreateBulk) OnConflictColumns(columns ...string) *UserPackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserPackageUpsertBulk{
		create: _c,
	}
}

// UserPackageUpsertBulk is the builder for "upsert"-ing
// a bulk of UserPackage nodes.
type UserPackageUpsertBulk struct {
	create *UserPackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserPackageUpsertBulk) UpdateNewValues() *UserPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userpackage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserPackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserPackageUpsertBulk) Ignore() *UserPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserPackageUpsertBulk) DoNothing() *UserPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserPackageCreateBulk.OnConflict
// documentation for more info.
func (u *UserPackageUpsertBulk) Update(set func(*UserPackageUpsert)) *UserPackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserPackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserPackageUpsertBulk) SetUpdatedAt(v time.Time) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateUpdatedAt() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserPackageUpsertBulk) SetUserID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserPackageUpsertBulk) AddUserID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateUserID() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserPackageUpsertBulk) SetGroupID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *UserPackageUpsertBulk) AddGroupID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateGroupID() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateGroupID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserPackageUpsertBulk) SetPlanID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *UserPackageUpsertBulk) AddPlanID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdatePlanID() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdatePlanID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *UserPackageUpsertBulk) SetOrderID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *UserPackageUpsertBulk) AddOrderID(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateOrderID() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *UserPackageUpsertBulk) ClearOrderID() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.ClearOrderID()
	})
}

// SetName sets the "name" field.
func (u *UserPackageUpsertBulk) SetName(v string) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateName() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateName()
	})
}

// SetCycle sets the "cycle" field.
func (u *UserPackageUpsertBulk) SetCycle(v string) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetCycle(v)
	})
}

// UpdateCycle sets the "cycle" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateCycle() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateCycle()
	})
}

// SetTier sets the "tier" field.
func (u *UserPackageUpsertBulk) SetTier(v int8) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetTier(v)
	})
}

// AddTier adds v to the "tier" field.
func (u *UserPackageUpsertBulk) AddTier(v int8) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddTier(v)
	})
}

// UpdateTier sets the "tier" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateTier() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateTier()
	})
}

// SetQuotaUsd sets the "quota_usd" field.
func (u *UserPackageUpsertBulk) SetQuotaUsd(v float64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetQuotaUsd(v)
	})
}

// AddQuotaUsd adds v to the "quota_usd" field.
func (u *UserPackageUpsertBulk) AddQuotaUsd(v float64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddQuotaUsd(v)
	})
}

// UpdateQuotaUsd sets the "quota_usd" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateQuotaUsd() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateQuotaUsd()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *UserPackageUpsertBulk) SetUsedUsd(v float64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *UserPackageUpsertBulk) AddUsedUsd(v float64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateUsedUsd() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserPackageUpsertBulk) SetStartsAt(v time.Time) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateStartsAt() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserPackageUpsertBulk) SetExpiresAt(v time.Time) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateExpiresAt() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserPackageUpsertBulk) SetStatus(v string) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateStatus() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateStatus()
	})
}

// SetFrozenAt sets the "frozen_at" field.
func (u *UserPackageUpsertBulk) SetFrozenAt(v time.Time) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetFrozenAt(v)
	})
}

// UpdateFrozenAt sets the "frozen_at" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateFrozenAt() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateFrozenAt()
	})
}

// ClearFrozenAt clears the value of the "frozen_at" field.
func (u *UserPackageUpsertBulk) ClearFrozenAt() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.ClearFrozenAt()
	})
}

// SetFrozenSecondsTotal sets the "frozen_seconds_total" field.
func (u *UserPackageUpsertBulk) SetFrozenSecondsTotal(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.SetFrozenSecondsTotal(v)
	})
}

// AddFrozenSecondsTotal adds v to the "frozen_seconds_total" field.
func (u *UserPackageUpsertBulk) AddFrozenSecondsTotal(v int64) *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.AddFrozenSecondsTotal(v)
	})
}

// UpdateFrozenSecondsTotal sets the "frozen_seconds_total" field to the value that was provided on create.
func (u *UserPackageUpsertBulk) UpdateFrozenSecondsTotal() *UserPackageUpsertBulk {
	return u.Update(func(s *UserPackageUpsert) {
		s.UpdateFrozenSecondsTotal()
	})
}

// Exec executes the query.
func (u *UserPackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserPackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserPackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserPackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
