// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/userpackagefreeze"
)

// UserPackageFreezeUpdate is the builder for updating UserPackageFreeze entities.
type UserPackageFreezeUpdate struct {
	config
	hooks    []Hook
	mutation *UserPackageFreezeMutation
}

// Where appends a list predicates to the UserPackageFreezeUpdate builder.
func (_u *UserPackageFreezeUpdate) Where(ps ...predicate.UserPackageFreeze) *UserPackageFreezeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPackageFreezeUpdate) SetUpdatedAt(v time.Time) *UserPackageFreezeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *UserPackageFreezeUpdate) SetPackageID(v int64) *UserPackageFreezeUpdate {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillablePackageID(v *int64) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *UserPackageFreezeUpdate) AddPackageID(v int64) *UserPackageFreezeUpdate {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPackageFreezeUpdate) SetUserID(v int64) *UserPackageFreezeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillableUserID(v *int64) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserPackageFreezeUpdate) AddUserID(v int64) *UserPackageFreezeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFrozenAt sets the "frozen_at" field.
func (_u *UserPackageFreezeUpdate) SetFrozenAt(v time.Time) *UserPackageFreezeUpdate {
	_u.mutation.SetFrozenAt(v)
	return _u
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillableFrozenAt(v *time.Time) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetFrozenAt(*v)
	}
	return _u
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (_u *UserPackageFreezeUpdate) SetUnfrozenAt(v time.Time) *UserPackageFreezeUpdate {
	_u.mutation.SetUnfrozenAt(v)
	return _u
}

// SetNillableUnfrozenAt sets the "unfrozen_at" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillableUnfrozenAt(v *time.Time) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetUnfrozenAt(*v)
	}
	return _u
}

// ClearUnfrozenAt clears the value of the "unfrozen_at" field.
func (_u *UserPackageFreezeUpdate) ClearUnfrozenAt() *UserPackageFreezeUpdate {
	_u.mutation.ClearUnfrozenAt()
	return _u
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (_u *UserPackageFreezeUpdate) SetUnfreezeReason(v string) *UserPackageFreezeUpdate {
	_u.mutation.SetUnfreezeReason(v)
	return _u
}

// SetNillableUnfreezeReason sets the "unfreeze_reason" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillableUnfreezeReason(v *string) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetUnfreezeReason(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *UserPackageFreezeUpdate) SetDurationSeconds(v int64) *UserPackageFreezeUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *UserPackageFreezeUpdate) SetNillableDurationSeconds(v *int64) *UserPackageFreezeUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *UserPackageFreezeUpdate) AddDurationSeconds(v int64) *UserPackageFreezeUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// Mutation returns the UserPackageFreezeMutation object of the builder.
func (_u *UserPackageFreezeUpdate) Mutation() *UserPackageFreezeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserPackageFreezeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPackageFreezeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserPackageFreezeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPackageFreezeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserPackageFreezeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userpackagefreeze.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPackageFreezeUpdate) check() error {
	if v, ok := _u.mutation.UnfreezeReason(); ok {
		if err := userpackagefreeze.UnfreezeReasonValidator(v); err != nil {
			return &ValidationError{Name: "unfreeze_reason", err: fmt.Errorf(`ent: validator failed for field "UserPackageFreeze.unfreeze_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UserPackageFreezeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpackagefreeze.Table, userpackagefreeze.Columns, sqlgraph.NewFieldSpec(userpackagefreeze.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(userpackagefreeze.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(userpackagefreeze.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userpackagefreeze.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userpackagefreeze.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldFrozenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnfrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfrozenAt, field.TypeTime, value)
	}
	if _u.mutation.UnfrozenAtCleared() {
		_spec.ClearField(userpackagefreeze.FieldUnfrozenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnfreezeReason(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfreezeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(userpackagefreeze.FieldDurationSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(userpackagefreeze.FieldDurationSeconds, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpackagefreeze.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserPackageFreezeUpdateOne is the builder for updating a single UserPackageFreeze entity.
type UserPackageFreezeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserPackageFreezeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserPackageFreezeUpdateOne) SetUpdatedAt(v time.Time) *UserPackageFreezeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *UserPackageFreezeUpdateOne) SetPackageID(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillablePackageID(v *int64) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *UserPackageFreezeUpdateOne) AddPackageID(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserPackageFreezeUpdateOne) SetUserID(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillableUserID(v *int64) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserPackageFreezeUpdateOne) AddUserID(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetFrozenAt sets the "frozen_at" field.
func (_u *UserPackageFreezeUpdateOne) SetFrozenAt(v time.Time) *UserPackageFreezeUpdateOne {
	_u.mutation.SetFrozenAt(v)
	return _u
}

// SetNillableFrozenAt sets the "frozen_at" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillableFrozenAt(v *time.Time) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetFrozenAt(*v)
	}
	return _u
}

// SetUnfrozenAt sets the "unfrozen_at" field.
func (_u *UserPackageFreezeUpdateOne) SetUnfrozenAt(v time.Time) *UserPackageFreezeUpdateOne {
	_u.mutation.SetUnfrozenAt(v)
	return _u
}

// SetNillableUnfrozenAt sets the "unfrozen_at" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillableUnfrozenAt(v *time.Time) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetUnfrozenAt(*v)
	}
	return _u
}

// ClearUnfrozenAt clears the value of the "unfrozen_at" field.
func (_u *UserPackageFreezeUpdateOne) ClearUnfrozenAt() *UserPackageFreezeUpdateOne {
	_u.mutation.ClearUnfrozenAt()
	return _u
}

// SetUnfreezeReason sets the "unfreeze_reason" field.
func (_u *UserPackageFreezeUpdateOne) SetUnfreezeReason(v string) *UserPackageFreezeUpdateOne {
	_u.mutation.SetUnfreezeReason(v)
	return _u
}

// SetNillableUnfreezeReason sets the "unfreeze_reason" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillableUnfreezeReason(v *string) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetUnfreezeReason(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *UserPackageFreezeUpdateOne) SetDurationSeconds(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *UserPackageFreezeUpdateOne) SetNillableDurationSeconds(v *int64) *UserPackageFreezeUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *UserPackageFreezeUpdateOne) AddDurationSeconds(v int64) *UserPackageFreezeUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// Mutation returns the UserPackageFreezeMutation object of the builder.
func (_u *UserPackageFreezeUpdateOne) Mutation() *UserPackageFreezeMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserPackageFreezeUpdate builder.
func (_u *UserPackageFreezeUpdateOne) Where(ps ...predicate.UserPackageFreeze) *UserPackageFreezeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserPackageFreezeUpdateOne) Select(field string, fields ...string) *UserPackageFreezeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserPackageFreeze entity.
func (_u *UserPackageFreezeUpdateOne) Save(ctx context.Context) (*UserPackageFreeze, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserPackageFreezeUpdateOne) SaveX(ctx context.Context) *UserPackageFreeze {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserPackageFreezeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserPackageFreezeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserPackageFreezeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userpackagefreeze.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserPackageFreezeUpdateOne) check() error {
	if v, ok := _u.mutation.UnfreezeReason(); ok {
		if err := userpackagefreeze.UnfreezeReasonValidator(v); err != nil {
			return &ValidationError{Name: "unfreeze_reason", err: fmt.Errorf(`ent: validator failed for field "UserPackageFreeze.unfreeze_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UserPackageFreezeUpdateOne) sqlSave(ctx context.Context) (_node *UserPackageFreeze, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userpackagefreeze.Table, userpackagefreeze.Columns, sqlgraph.NewFieldSpec(userpackagefreeze.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserPackageFreeze.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpackagefreeze.FieldID)
		for _, f := range fields {
			if !userpackagefreeze.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userpackagefreeze.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(userpackagefreeze.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(userpackagefreeze.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userpackagefreeze.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(userpackagefreeze.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldFrozenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UnfrozenAt(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfrozenAt, field.TypeTime, value)
	}
	if _u.mutation.UnfrozenAtCleared() {
		_spec.ClearField(userpackagefreeze.FieldUnfrozenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UnfreezeReason(); ok {
		_spec.SetField(userpackagefreeze.FieldUnfreezeReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(userpackagefreeze.FieldDurationSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(userpackagefreeze.FieldDurationSeconds, field.TypeInt64, value)
	}
	_node = &UserPackageFreeze{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userpackagefreeze.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
