// Code generated by ent, DO NOT EDIT.

package intelcheckquestion

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the intelcheckquestion type in the database.
	Label = "intel_check_question"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldExpectedAnswer holds the string denoting the expected_answer field in the database.
	FieldExpectedAnswer = "expected_answer"
	// FieldMatchMode holds the string denoting the match_mode field in the database.
	FieldMatchMode = "match_mode"
	// FieldReferenceHTML holds the string denoting the reference_html field in the database.
	FieldReferenceHTML = "reference_html"
	// FieldReferenceMetrics holds the string denoting the reference_metrics field in the database.
	FieldReferenceMetrics = "reference_metrics"
	// FieldDrawingRules holds the string denoting the drawing_rules field in the database.
	FieldDrawingRules = "drawing_rules"
	// FieldReviewRubric holds the string denoting the review_rubric field in the database.
	FieldReviewRubric = "review_rubric"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// Table holds the table name of the intelcheckquestion in the database.
	Table = "intel_check_questions"
)

// Columns holds all SQL columns for intelcheckquestion fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldKind,
	FieldTitle,
	FieldPrompt,
	FieldExpectedAnswer,
	FieldMatchMode,
	FieldReferenceHTML,
	FieldReferenceMetrics,
	FieldDrawingRules,
	FieldReviewRubric,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// PromptValidator is a validator for the "prompt" field. It is called by the builders before save.
	PromptValidator func(string) error
	// DefaultExpectedAnswer holds the default value on creation for the "expected_answer" field.
	DefaultExpectedAnswer string
	// ExpectedAnswerValidator is a validator for the "expected_answer" field. It is called by the builders before save.
	ExpectedAnswerValidator func(string) error
	// DefaultMatchMode holds the default value on creation for the "match_mode" field.
	DefaultMatchMode string
	// MatchModeValidator is a validator for the "match_mode" field. It is called by the builders before save.
	MatchModeValidator func(string) error
	// DefaultReferenceHTML holds the default value on creation for the "reference_html" field.
	DefaultReferenceHTML string
	// DefaultReviewRubric holds the default value on creation for the "review_rubric" field.
	DefaultReviewRubric string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// Kind defines the type for the "kind" enum field.
type Kind string

// Kind values.
const (
	KindLogic   Kind = "logic"
	KindDrawing Kind = "drawing"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindLogic, KindDrawing:
		return nil
	default:
		return fmt.Errorf("intelcheckquestion: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the IntelCheckQuestion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByExpectedAnswer orders the results by the expected_answer field.
func ByExpectedAnswer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpectedAnswer, opts...).ToFunc()
}

// ByMatchMode orders the results by the match_mode field.
func ByMatchMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchMode, opts...).ToFunc()
}

// ByReferenceHTML orders the results by the reference_html field.
func ByReferenceHTML(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceHTML, opts...).ToFunc()
}

// ByReviewRubric orders the results by the review_rubric field.
func ByReviewRubric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewRubric, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}
