// Code generated by ent, DO NOT EDIT.

package intelcheckquestion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldUpdatedAt, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldTitle, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldPrompt, v))
}

// ExpectedAnswer applies equality check predicate on the "expected_answer" field. It's identical to ExpectedAnswerEQ.
func ExpectedAnswer(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldExpectedAnswer, v))
}

// MatchMode applies equality check predicate on the "match_mode" field. It's identical to MatchModeEQ.
func MatchMode(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldMatchMode, v))
}

// ReferenceHTML applies equality check predicate on the "reference_html" field. It's identical to ReferenceHTMLEQ.
func ReferenceHTML(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldReferenceHTML, v))
}

// ReviewRubric applies equality check predicate on the "review_rubric" field. It's identical to ReviewRubricEQ.
func ReviewRubric(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldReviewRubric, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldKind, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldTitle, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldPrompt, v))
}

// ExpectedAnswerEQ applies the EQ predicate on the "expected_answer" field.
func ExpectedAnswerEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldExpectedAnswer, v))
}

// ExpectedAnswerNEQ applies the NEQ predicate on the "expected_answer" field.
func ExpectedAnswerNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldExpectedAnswer, v))
}

// ExpectedAnswerIn applies the In predicate on the "expected_answer" field.
func ExpectedAnswerIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldExpectedAnswer, vs...))
}

// ExpectedAnswerNotIn applies the NotIn predicate on the "expected_answer" field.
func ExpectedAnswerNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldExpectedAnswer, vs...))
}

// ExpectedAnswerGT applies the GT predicate on the "expected_answer" field.
func ExpectedAnswerGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldExpectedAnswer, v))
}

// ExpectedAnswerGTE applies the GTE predicate on the "expected_answer" field.
func ExpectedAnswerGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldExpectedAnswer, v))
}

// ExpectedAnswerLT applies the LT predicate on the "expected_answer" field.
func ExpectedAnswerLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldExpectedAnswer, v))
}

// ExpectedAnswerLTE applies the LTE predicate on the "expected_answer" field.
func ExpectedAnswerLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldExpectedAnswer, v))
}

// ExpectedAnswerContains applies the Contains predicate on the "expected_answer" field.
func ExpectedAnswerContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldExpectedAnswer, v))
}

// ExpectedAnswerHasPrefix applies the HasPrefix predicate on the "expected_answer" field.
func ExpectedAnswerHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldExpectedAnswer, v))
}

// ExpectedAnswerHasSuffix applies the HasSuffix predicate on the "expected_answer" field.
func ExpectedAnswerHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldExpectedAnswer, v))
}

// ExpectedAnswerIsNil applies the IsNil predicate on the "expected_answer" field.
func ExpectedAnswerIsNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIsNull(FieldExpectedAnswer))
}

// ExpectedAnswerNotNil applies the NotNil predicate on the "expected_answer" field.
func ExpectedAnswerNotNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotNull(FieldExpectedAnswer))
}

// ExpectedAnswerEqualFold applies the EqualFold predicate on the "expected_answer" field.
func ExpectedAnswerEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldExpectedAnswer, v))
}

// ExpectedAnswerContainsFold applies the ContainsFold predicate on the "expected_answer" field.
func ExpectedAnswerContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldExpectedAnswer, v))
}

// MatchModeEQ applies the EQ predicate on the "match_mode" field.
func MatchModeEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldMatchMode, v))
}

// MatchModeNEQ applies the NEQ predicate on the "match_mode" field.
func MatchModeNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldMatchMode, v))
}

// MatchModeIn applies the In predicate on the "match_mode" field.
func MatchModeIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldMatchMode, vs...))
}

// MatchModeNotIn applies the NotIn predicate on the "match_mode" field.
func MatchModeNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldMatchMode, vs...))
}

// MatchModeGT applies the GT predicate on the "match_mode" field.
func MatchModeGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldMatchMode, v))
}

// MatchModeGTE applies the GTE predicate on the "match_mode" field.
func MatchModeGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldMatchMode, v))
}

// MatchModeLT applies the LT predicate on the "match_mode" field.
func MatchModeLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldMatchMode, v))
}

// MatchModeLTE applies the LTE predicate on the "match_mode" field.
func MatchModeLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldMatchMode, v))
}

// MatchModeContains applies the Contains predicate on the "match_mode" field.
func MatchModeContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldMatchMode, v))
}

// MatchModeHasPrefix applies the HasPrefix predicate on the "match_mode" field.
func MatchModeHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldMatchMode, v))
}

// MatchModeHasSuffix applies the HasSuffix predicate on the "match_mode" field.
func MatchModeHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldMatchMode, v))
}

// MatchModeEqualFold applies the EqualFold predicate on the "match_mode" field.
func MatchModeEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldMatchMode, v))
}

// MatchModeContainsFold applies the ContainsFold predicate on the "match_mode" field.
func MatchModeContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldMatchMode, v))
}

// ReferenceHTMLEQ applies the EQ predicate on the "reference_html" field.
func ReferenceHTMLEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldReferenceHTML, v))
}

// ReferenceHTMLNEQ applies the NEQ predicate on the "reference_html" field.
func ReferenceHTMLNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldReferenceHTML, v))
}

// ReferenceHTMLIn applies the In predicate on the "reference_html" field.
func ReferenceHTMLIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldReferenceHTML, vs...))
}

// ReferenceHTMLNotIn applies the NotIn predicate on the "reference_html" field.
func ReferenceHTMLNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldReferenceHTML, vs...))
}

// ReferenceHTMLGT applies the GT predicate on the "reference_html" field.
func ReferenceHTMLGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldReferenceHTML, v))
}

// ReferenceHTMLGTE applies the GTE predicate on the "reference_html" field.
func ReferenceHTMLGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldReferenceHTML, v))
}

// ReferenceHTMLLT applies the LT predicate on the "reference_html" field.
func ReferenceHTMLLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldReferenceHTML, v))
}

// ReferenceHTMLLTE applies the LTE predicate on the "reference_html" field.
func ReferenceHTMLLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldReferenceHTML, v))
}

// ReferenceHTMLContains applies the Contains predicate on the "reference_html" field.
func ReferenceHTMLContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldReferenceHTML, v))
}

// ReferenceHTMLHasPrefix applies the HasPrefix predicate on the "reference_html" field.
func ReferenceHTMLHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldReferenceHTML, v))
}

// ReferenceHTMLHasSuffix applies the HasSuffix predicate on the "reference_html" field.
func ReferenceHTMLHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldReferenceHTML, v))
}

// ReferenceHTMLIsNil applies the IsNil predicate on the "reference_html" field.
func ReferenceHTMLIsNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIsNull(FieldReferenceHTML))
}

// ReferenceHTMLNotNil applies the NotNil predicate on the "reference_html" field.
func ReferenceHTMLNotNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotNull(FieldReferenceHTML))
}

// ReferenceHTMLEqualFold applies the EqualFold predicate on the "reference_html" field.
func ReferenceHTMLEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldReferenceHTML, v))
}

// ReferenceHTMLContainsFold applies the ContainsFold predicate on the "reference_html" field.
func ReferenceHTMLContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldReferenceHTML, v))
}

// ReferenceMetricsIsNil applies the IsNil predicate on the "reference_metrics" field.
func ReferenceMetricsIsNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIsNull(FieldReferenceMetrics))
}

// ReferenceMetricsNotNil applies the NotNil predicate on the "reference_metrics" field.
func ReferenceMetricsNotNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotNull(FieldReferenceMetrics))
}

// DrawingRulesIsNil applies the IsNil predicate on the "drawing_rules" field.
func DrawingRulesIsNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIsNull(FieldDrawingRules))
}

// DrawingRulesNotNil applies the NotNil predicate on the "drawing_rules" field.
func DrawingRulesNotNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotNull(FieldDrawingRules))
}

// ReviewRubricEQ applies the EQ predicate on the "review_rubric" field.
func ReviewRubricEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldReviewRubric, v))
}

// ReviewRubricNEQ applies the NEQ predicate on the "review_rubric" field.
func ReviewRubricNEQ(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldReviewRubric, v))
}

// ReviewRubricIn applies the In predicate on the "review_rubric" field.
func ReviewRubricIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIn(FieldReviewRubric, vs...))
}

// ReviewRubricNotIn applies the NotIn predicate on the "review_rubric" field.
func ReviewRubricNotIn(vs ...string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotIn(FieldReviewRubric, vs...))
}

// ReviewRubricGT applies the GT predicate on the "review_rubric" field.
func ReviewRubricGT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGT(FieldReviewRubric, v))
}

// ReviewRubricGTE applies the GTE predicate on the "review_rubric" field.
func ReviewRubricGTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldGTE(FieldReviewRubric, v))
}

// ReviewRubricLT applies the LT predicate on the "review_rubric" field.
func ReviewRubricLT(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLT(FieldReviewRubric, v))
}

// ReviewRubricLTE applies the LTE predicate on the "review_rubric" field.
func ReviewRubricLTE(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldLTE(FieldReviewRubric, v))
}

// ReviewRubricContains applies the Contains predicate on the "review_rubric" field.
func ReviewRubricContains(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContains(FieldReviewRubric, v))
}

// ReviewRubricHasPrefix applies the HasPrefix predicate on the "review_rubric" field.
func ReviewRubricHasPrefix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasPrefix(FieldReviewRubric, v))
}

// ReviewRubricHasSuffix applies the HasSuffix predicate on the "review_rubric" field.
func ReviewRubricHasSuffix(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldHasSuffix(FieldReviewRubric, v))
}

// ReviewRubricIsNil applies the IsNil predicate on the "review_rubric" field.
func ReviewRubricIsNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldIsNull(FieldReviewRubric))
}

// ReviewRubricNotNil applies the NotNil predicate on the "review_rubric" field.
func ReviewRubricNotNil() predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNotNull(FieldReviewRubric))
}

// ReviewRubricEqualFold applies the EqualFold predicate on the "review_rubric" field.
func ReviewRubricEqualFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEqualFold(FieldReviewRubric, v))
}

// ReviewRubricContainsFold applies the ContainsFold predicate on the "review_rubric" field.
func ReviewRubricContainsFold(v string) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldContainsFold(FieldReviewRubric, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntelCheckQuestion) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntelCheckQuestion) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntelCheckQuestion) predicate.IntelCheckQuestion {
	return predicate.IntelCheckQuestion(sql.NotPredicates(p))
}
