// Code generated by ent, DO NOT EDIT.

package intelcheckround

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldID, id))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldSeq, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldFinishedAt, v))
}

// LogicQuestionID applies equality check predicate on the "logic_question_id" field. It's identical to LogicQuestionIDEQ.
func LogicQuestionID(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldLogicQuestionID, v))
}

// DrawingQuestionID applies equality check predicate on the "drawing_question_id" field. It's identical to DrawingQuestionIDEQ.
func DrawingQuestionID(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldDrawingQuestionID, v))
}

// TriggerSource applies equality check predicate on the "trigger_source" field. It's identical to TriggerSourceEQ.
func TriggerSource(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldTriggerSource, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldSeq, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotNull(FieldFinishedAt))
}

// LogicQuestionIDEQ applies the EQ predicate on the "logic_question_id" field.
func LogicQuestionIDEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldLogicQuestionID, v))
}

// LogicQuestionIDNEQ applies the NEQ predicate on the "logic_question_id" field.
func LogicQuestionIDNEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldLogicQuestionID, v))
}

// LogicQuestionIDIn applies the In predicate on the "logic_question_id" field.
func LogicQuestionIDIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldLogicQuestionID, vs...))
}

// LogicQuestionIDNotIn applies the NotIn predicate on the "logic_question_id" field.
func LogicQuestionIDNotIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldLogicQuestionID, vs...))
}

// LogicQuestionIDGT applies the GT predicate on the "logic_question_id" field.
func LogicQuestionIDGT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldLogicQuestionID, v))
}

// LogicQuestionIDGTE applies the GTE predicate on the "logic_question_id" field.
func LogicQuestionIDGTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldLogicQuestionID, v))
}

// LogicQuestionIDLT applies the LT predicate on the "logic_question_id" field.
func LogicQuestionIDLT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldLogicQuestionID, v))
}

// LogicQuestionIDLTE applies the LTE predicate on the "logic_question_id" field.
func LogicQuestionIDLTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldLogicQuestionID, v))
}

// LogicQuestionIDIsNil applies the IsNil predicate on the "logic_question_id" field.
func LogicQuestionIDIsNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIsNull(FieldLogicQuestionID))
}

// LogicQuestionIDNotNil applies the NotNil predicate on the "logic_question_id" field.
func LogicQuestionIDNotNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotNull(FieldLogicQuestionID))
}

// DrawingQuestionIDEQ applies the EQ predicate on the "drawing_question_id" field.
func DrawingQuestionIDEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDNEQ applies the NEQ predicate on the "drawing_question_id" field.
func DrawingQuestionIDNEQ(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDIn applies the In predicate on the "drawing_question_id" field.
func DrawingQuestionIDIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldDrawingQuestionID, vs...))
}

// DrawingQuestionIDNotIn applies the NotIn predicate on the "drawing_question_id" field.
func DrawingQuestionIDNotIn(vs ...int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldDrawingQuestionID, vs...))
}

// DrawingQuestionIDGT applies the GT predicate on the "drawing_question_id" field.
func DrawingQuestionIDGT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDGTE applies the GTE predicate on the "drawing_question_id" field.
func DrawingQuestionIDGTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDLT applies the LT predicate on the "drawing_question_id" field.
func DrawingQuestionIDLT(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDLTE applies the LTE predicate on the "drawing_question_id" field.
func DrawingQuestionIDLTE(v int64) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldDrawingQuestionID, v))
}

// DrawingQuestionIDIsNil applies the IsNil predicate on the "drawing_question_id" field.
func DrawingQuestionIDIsNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIsNull(FieldDrawingQuestionID))
}

// DrawingQuestionIDNotNil applies the NotNil predicate on the "drawing_question_id" field.
func DrawingQuestionIDNotNil() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotNull(FieldDrawingQuestionID))
}

// TriggerSourceEQ applies the EQ predicate on the "trigger_source" field.
func TriggerSourceEQ(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEQ(FieldTriggerSource, v))
}

// TriggerSourceNEQ applies the NEQ predicate on the "trigger_source" field.
func TriggerSourceNEQ(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNEQ(FieldTriggerSource, v))
}

// TriggerSourceIn applies the In predicate on the "trigger_source" field.
func TriggerSourceIn(vs ...string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldIn(FieldTriggerSource, vs...))
}

// TriggerSourceNotIn applies the NotIn predicate on the "trigger_source" field.
func TriggerSourceNotIn(vs ...string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldNotIn(FieldTriggerSource, vs...))
}

// TriggerSourceGT applies the GT predicate on the "trigger_source" field.
func TriggerSourceGT(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGT(FieldTriggerSource, v))
}

// TriggerSourceGTE applies the GTE predicate on the "trigger_source" field.
func TriggerSourceGTE(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldGTE(FieldTriggerSource, v))
}

// TriggerSourceLT applies the LT predicate on the "trigger_source" field.
func TriggerSourceLT(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLT(FieldTriggerSource, v))
}

// TriggerSourceLTE applies the LTE predicate on the "trigger_source" field.
func TriggerSourceLTE(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldLTE(FieldTriggerSource, v))
}

// TriggerSourceContains applies the Contains predicate on the "trigger_source" field.
func TriggerSourceContains(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldContains(FieldTriggerSource, v))
}

// TriggerSourceHasPrefix applies the HasPrefix predicate on the "trigger_source" field.
func TriggerSourceHasPrefix(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldHasPrefix(FieldTriggerSource, v))
}

// TriggerSourceHasSuffix applies the HasSuffix predicate on the "trigger_source" field.
func TriggerSourceHasSuffix(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldHasSuffix(FieldTriggerSource, v))
}

// TriggerSourceEqualFold applies the EqualFold predicate on the "trigger_source" field.
func TriggerSourceEqualFold(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldEqualFold(FieldTriggerSource, v))
}

// TriggerSourceContainsFold applies the ContainsFold predicate on the "trigger_source" field.
func TriggerSourceContainsFold(v string) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.FieldContainsFold(FieldTriggerSource, v))
}

// HasResults applies the HasEdge predicate on the "results" edge.
func HasResults() predicate.IntelCheckRound {
	return predicate.IntelCheckRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResultsWith applies the HasEdge predicate on the "results" edge with a given conditions (other predicates).
func HasResultsWith(preds ...predicate.IntelCheckResult) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(func(s *sql.Selector) {
		step := newResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntelCheckRound) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntelCheckRound) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntelCheckRound) predicate.IntelCheckRound {
	return predicate.IntelCheckRound(sql.NotPredicates(p))
}
