// Code generated by ent, DO NOT EDIT.

package intelcheckresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldID, id))
}

// RoundID applies equality check predicate on the "round_id" field. It's identical to RoundIDEQ.
func RoundID(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldRoundID, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldTargetID, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldLatencyMs, v))
}

// PromptSnapshot applies equality check predicate on the "prompt_snapshot" field. It's identical to PromptSnapshotEQ.
func PromptSnapshot(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldPromptSnapshot, v))
}

// RawReply applies equality check predicate on the "raw_reply" field. It's identical to RawReplyEQ.
func RawReply(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldRawReply, v))
}

// ExtractedAnswer applies equality check predicate on the "extracted_answer" field. It's identical to ExtractedAnswerEQ.
func ExtractedAnswer(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldExtractedAnswer, v))
}

// HTMLOutput applies equality check predicate on the "html_output" field. It's identical to HTMLOutputEQ.
func HTMLOutput(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldHTMLOutput, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldErrorMessage, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldOutputTokens, v))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldCheckedAt, v))
}

// RoundIDEQ applies the EQ predicate on the "round_id" field.
func RoundIDEQ(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldRoundID, v))
}

// RoundIDNEQ applies the NEQ predicate on the "round_id" field.
func RoundIDNEQ(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldRoundID, v))
}

// RoundIDIn applies the In predicate on the "round_id" field.
func RoundIDIn(vs ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldRoundID, vs...))
}

// RoundIDNotIn applies the NotIn predicate on the "round_id" field.
func RoundIDNotIn(vs ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldRoundID, vs...))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...int64) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldTargetID, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v Kind) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v Kind) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...Kind) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...Kind) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldKind, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldStatus, vs...))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldLatencyMs))
}

// PromptSnapshotEQ applies the EQ predicate on the "prompt_snapshot" field.
func PromptSnapshotEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldPromptSnapshot, v))
}

// PromptSnapshotNEQ applies the NEQ predicate on the "prompt_snapshot" field.
func PromptSnapshotNEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldPromptSnapshot, v))
}

// PromptSnapshotIn applies the In predicate on the "prompt_snapshot" field.
func PromptSnapshotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldPromptSnapshot, vs...))
}

// PromptSnapshotNotIn applies the NotIn predicate on the "prompt_snapshot" field.
func PromptSnapshotNotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldPromptSnapshot, vs...))
}

// PromptSnapshotGT applies the GT predicate on the "prompt_snapshot" field.
func PromptSnapshotGT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldPromptSnapshot, v))
}

// PromptSnapshotGTE applies the GTE predicate on the "prompt_snapshot" field.
func PromptSnapshotGTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldPromptSnapshot, v))
}

// PromptSnapshotLT applies the LT predicate on the "prompt_snapshot" field.
func PromptSnapshotLT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldPromptSnapshot, v))
}

// PromptSnapshotLTE applies the LTE predicate on the "prompt_snapshot" field.
func PromptSnapshotLTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldPromptSnapshot, v))
}

// PromptSnapshotContains applies the Contains predicate on the "prompt_snapshot" field.
func PromptSnapshotContains(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContains(FieldPromptSnapshot, v))
}

// PromptSnapshotHasPrefix applies the HasPrefix predicate on the "prompt_snapshot" field.
func PromptSnapshotHasPrefix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasPrefix(FieldPromptSnapshot, v))
}

// PromptSnapshotHasSuffix applies the HasSuffix predicate on the "prompt_snapshot" field.
func PromptSnapshotHasSuffix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasSuffix(FieldPromptSnapshot, v))
}

// PromptSnapshotIsNil applies the IsNil predicate on the "prompt_snapshot" field.
func PromptSnapshotIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldPromptSnapshot))
}

// PromptSnapshotNotNil applies the NotNil predicate on the "prompt_snapshot" field.
func PromptSnapshotNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldPromptSnapshot))
}

// PromptSnapshotEqualFold applies the EqualFold predicate on the "prompt_snapshot" field.
func PromptSnapshotEqualFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEqualFold(FieldPromptSnapshot, v))
}

// PromptSnapshotContainsFold applies the ContainsFold predicate on the "prompt_snapshot" field.
func PromptSnapshotContainsFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContainsFold(FieldPromptSnapshot, v))
}

// RawReplyEQ applies the EQ predicate on the "raw_reply" field.
func RawReplyEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldRawReply, v))
}

// RawReplyNEQ applies the NEQ predicate on the "raw_reply" field.
func RawReplyNEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldRawReply, v))
}

// RawReplyIn applies the In predicate on the "raw_reply" field.
func RawReplyIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldRawReply, vs...))
}

// RawReplyNotIn applies the NotIn predicate on the "raw_reply" field.
func RawReplyNotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldRawReply, vs...))
}

// RawReplyGT applies the GT predicate on the "raw_reply" field.
func RawReplyGT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldRawReply, v))
}

// RawReplyGTE applies the GTE predicate on the "raw_reply" field.
func RawReplyGTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldRawReply, v))
}

// RawReplyLT applies the LT predicate on the "raw_reply" field.
func RawReplyLT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldRawReply, v))
}

// RawReplyLTE applies the LTE predicate on the "raw_reply" field.
func RawReplyLTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldRawReply, v))
}

// RawReplyContains applies the Contains predicate on the "raw_reply" field.
func RawReplyContains(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContains(FieldRawReply, v))
}

// RawReplyHasPrefix applies the HasPrefix predicate on the "raw_reply" field.
func RawReplyHasPrefix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasPrefix(FieldRawReply, v))
}

// RawReplyHasSuffix applies the HasSuffix predicate on the "raw_reply" field.
func RawReplyHasSuffix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasSuffix(FieldRawReply, v))
}

// RawReplyIsNil applies the IsNil predicate on the "raw_reply" field.
func RawReplyIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldRawReply))
}

// RawReplyNotNil applies the NotNil predicate on the "raw_reply" field.
func RawReplyNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldRawReply))
}

// RawReplyEqualFold applies the EqualFold predicate on the "raw_reply" field.
func RawReplyEqualFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEqualFold(FieldRawReply, v))
}

// RawReplyContainsFold applies the ContainsFold predicate on the "raw_reply" field.
func RawReplyContainsFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContainsFold(FieldRawReply, v))
}

// ExtractedAnswerEQ applies the EQ predicate on the "extracted_answer" field.
func ExtractedAnswerEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldExtractedAnswer, v))
}

// ExtractedAnswerNEQ applies the NEQ predicate on the "extracted_answer" field.
func ExtractedAnswerNEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldExtractedAnswer, v))
}

// ExtractedAnswerIn applies the In predicate on the "extracted_answer" field.
func ExtractedAnswerIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldExtractedAnswer, vs...))
}

// ExtractedAnswerNotIn applies the NotIn predicate on the "extracted_answer" field.
func ExtractedAnswerNotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldExtractedAnswer, vs...))
}

// ExtractedAnswerGT applies the GT predicate on the "extracted_answer" field.
func ExtractedAnswerGT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldExtractedAnswer, v))
}

// ExtractedAnswerGTE applies the GTE predicate on the "extracted_answer" field.
func ExtractedAnswerGTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldExtractedAnswer, v))
}

// ExtractedAnswerLT applies the LT predicate on the "extracted_answer" field.
func ExtractedAnswerLT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldExtractedAnswer, v))
}

// ExtractedAnswerLTE applies the LTE predicate on the "extracted_answer" field.
func ExtractedAnswerLTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldExtractedAnswer, v))
}

// ExtractedAnswerContains applies the Contains predicate on the "extracted_answer" field.
func ExtractedAnswerContains(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContains(FieldExtractedAnswer, v))
}

// ExtractedAnswerHasPrefix applies the HasPrefix predicate on the "extracted_answer" field.
func ExtractedAnswerHasPrefix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasPrefix(FieldExtractedAnswer, v))
}

// ExtractedAnswerHasSuffix applies the HasSuffix predicate on the "extracted_answer" field.
func ExtractedAnswerHasSuffix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasSuffix(FieldExtractedAnswer, v))
}

// ExtractedAnswerIsNil applies the IsNil predicate on the "extracted_answer" field.
func ExtractedAnswerIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldExtractedAnswer))
}

// ExtractedAnswerNotNil applies the NotNil predicate on the "extracted_answer" field.
func ExtractedAnswerNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldExtractedAnswer))
}

// ExtractedAnswerEqualFold applies the EqualFold predicate on the "extracted_answer" field.
func ExtractedAnswerEqualFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEqualFold(FieldExtractedAnswer, v))
}

// ExtractedAnswerContainsFold applies the ContainsFold predicate on the "extracted_answer" field.
func ExtractedAnswerContainsFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContainsFold(FieldExtractedAnswer, v))
}

// HTMLOutputEQ applies the EQ predicate on the "html_output" field.
func HTMLOutputEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldHTMLOutput, v))
}

// HTMLOutputNEQ applies the NEQ predicate on the "html_output" field.
func HTMLOutputNEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldHTMLOutput, v))
}

// HTMLOutputIn applies the In predicate on the "html_output" field.
func HTMLOutputIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldHTMLOutput, vs...))
}

// HTMLOutputNotIn applies the NotIn predicate on the "html_output" field.
func HTMLOutputNotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldHTMLOutput, vs...))
}

// HTMLOutputGT applies the GT predicate on the "html_output" field.
func HTMLOutputGT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldHTMLOutput, v))
}

// HTMLOutputGTE applies the GTE predicate on the "html_output" field.
func HTMLOutputGTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldHTMLOutput, v))
}

// HTMLOutputLT applies the LT predicate on the "html_output" field.
func HTMLOutputLT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldHTMLOutput, v))
}

// HTMLOutputLTE applies the LTE predicate on the "html_output" field.
func HTMLOutputLTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldHTMLOutput, v))
}

// HTMLOutputContains applies the Contains predicate on the "html_output" field.
func HTMLOutputContains(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContains(FieldHTMLOutput, v))
}

// HTMLOutputHasPrefix applies the HasPrefix predicate on the "html_output" field.
func HTMLOutputHasPrefix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasPrefix(FieldHTMLOutput, v))
}

// HTMLOutputHasSuffix applies the HasSuffix predicate on the "html_output" field.
func HTMLOutputHasSuffix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasSuffix(FieldHTMLOutput, v))
}

// HTMLOutputIsNil applies the IsNil predicate on the "html_output" field.
func HTMLOutputIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldHTMLOutput))
}

// HTMLOutputNotNil applies the NotNil predicate on the "html_output" field.
func HTMLOutputNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldHTMLOutput))
}

// HTMLOutputEqualFold applies the EqualFold predicate on the "html_output" field.
func HTMLOutputEqualFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEqualFold(FieldHTMLOutput, v))
}

// HTMLOutputContainsFold applies the ContainsFold predicate on the "html_output" field.
func HTMLOutputContainsFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContainsFold(FieldHTMLOutput, v))
}

// JudgeDetailIsNil applies the IsNil predicate on the "judge_detail" field.
func JudgeDetailIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldJudgeDetail))
}

// JudgeDetailNotNil applies the NotNil predicate on the "judge_detail" field.
func JudgeDetailNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldJudgeDetail))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldContainsFold(FieldErrorMessage, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldInputTokens, v))
}

// InputTokensIsNil applies the IsNil predicate on the "input_tokens" field.
func InputTokensIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldInputTokens))
}

// InputTokensNotNil applies the NotNil predicate on the "input_tokens" field.
func InputTokensNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldInputTokens))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldOutputTokens, v))
}

// OutputTokensIsNil applies the IsNil predicate on the "output_tokens" field.
func OutputTokensIsNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIsNull(FieldOutputTokens))
}

// OutputTokensNotNil applies the NotNil predicate on the "output_tokens" field.
func OutputTokensNotNil() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotNull(FieldOutputTokens))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.FieldLTE(FieldCheckedAt, v))
}

// HasRound applies the HasEdge predicate on the "round" edge.
func HasRound() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoundTable, RoundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoundWith applies the HasEdge predicate on the "round" edge with a given conditions (other predicates).
func HasRoundWith(preds ...predicate.IntelCheckRound) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(func(s *sql.Selector) {
		step := newRoundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.IntelCheckResult {
	return predicate.IntelCheckResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.IntelCheckTarget) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntelCheckResult) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntelCheckResult) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntelCheckResult) predicate.IntelCheckResult {
	return predicate.IntelCheckResult(sql.NotPredicates(p))
}
