// Code generated by ent, DO NOT EDIT.

package userpackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldGroupID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldPlanID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldOrderID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldName, v))
}

// Cycle applies equality check predicate on the "cycle" field. It's identical to CycleEQ.
func Cycle(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldCycle, v))
}

// Tier applies equality check predicate on the "tier" field. It's identical to TierEQ.
func Tier(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldTier, v))
}

// QuotaUsd applies equality check predicate on the "quota_usd" field. It's identical to QuotaUsdEQ.
func QuotaUsd(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldQuotaUsd, v))
}

// UsedUsd applies equality check predicate on the "used_usd" field. It's identical to UsedUsdEQ.
func UsedUsd(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUsedUsd, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldStatus, v))
}

// FrozenAt applies equality check predicate on the "frozen_at" field. It's identical to FrozenAtEQ.
func FrozenAt(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldFrozenAt, v))
}

// FrozenSecondsTotal applies equality check predicate on the "frozen_seconds_total" field. It's identical to FrozenSecondsTotalEQ.
func FrozenSecondsTotal(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldFrozenSecondsTotal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldGroupID, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDGT applies the GT predicate on the "plan_id" field.
func PlanIDGT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldPlanID, v))
}

// PlanIDGTE applies the GTE predicate on the "plan_id" field.
func PlanIDGTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldPlanID, v))
}

// PlanIDLT applies the LT predicate on the "plan_id" field.
func PlanIDLT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldPlanID, v))
}

// PlanIDLTE applies the LTE predicate on the "plan_id" field.
func PlanIDLTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldPlanID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotNull(FieldOrderID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContainsFold(FieldName, v))
}

// CycleEQ applies the EQ predicate on the "cycle" field.
func CycleEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldCycle, v))
}

// CycleNEQ applies the NEQ predicate on the "cycle" field.
func CycleNEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldCycle, v))
}

// CycleIn applies the In predicate on the "cycle" field.
func CycleIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldCycle, vs...))
}

// CycleNotIn applies the NotIn predicate on the "cycle" field.
func CycleNotIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldCycle, vs...))
}

// CycleGT applies the GT predicate on the "cycle" field.
func CycleGT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldCycle, v))
}

// CycleGTE applies the GTE predicate on the "cycle" field.
func CycleGTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldCycle, v))
}

// CycleLT applies the LT predicate on the "cycle" field.
func CycleLT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldCycle, v))
}

// CycleLTE applies the LTE predicate on the "cycle" field.
func CycleLTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldCycle, v))
}

// CycleContains applies the Contains predicate on the "cycle" field.
func CycleContains(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContains(FieldCycle, v))
}

// CycleHasPrefix applies the HasPrefix predicate on the "cycle" field.
func CycleHasPrefix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasPrefix(FieldCycle, v))
}

// CycleHasSuffix applies the HasSuffix predicate on the "cycle" field.
func CycleHasSuffix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasSuffix(FieldCycle, v))
}

// CycleEqualFold applies the EqualFold predicate on the "cycle" field.
func CycleEqualFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEqualFold(FieldCycle, v))
}

// CycleContainsFold applies the ContainsFold predicate on the "cycle" field.
func CycleContainsFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContainsFold(FieldCycle, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldTier, vs...))
}

// TierGT applies the GT predicate on the "tier" field.
func TierGT(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldTier, v))
}

// TierGTE applies the GTE predicate on the "tier" field.
func TierGTE(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldTier, v))
}

// TierLT applies the LT predicate on the "tier" field.
func TierLT(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldTier, v))
}

// TierLTE applies the LTE predicate on the "tier" field.
func TierLTE(v int8) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldTier, v))
}

// QuotaUsdEQ applies the EQ predicate on the "quota_usd" field.
func QuotaUsdEQ(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldQuotaUsd, v))
}

// QuotaUsdNEQ applies the NEQ predicate on the "quota_usd" field.
func QuotaUsdNEQ(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldQuotaUsd, v))
}

// QuotaUsdIn applies the In predicate on the "quota_usd" field.
func QuotaUsdIn(vs ...float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldQuotaUsd, vs...))
}

// QuotaUsdNotIn applies the NotIn predicate on the "quota_usd" field.
func QuotaUsdNotIn(vs ...float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldQuotaUsd, vs...))
}

// QuotaUsdGT applies the GT predicate on the "quota_usd" field.
func QuotaUsdGT(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldQuotaUsd, v))
}

// QuotaUsdGTE applies the GTE predicate on the "quota_usd" field.
func QuotaUsdGTE(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldQuotaUsd, v))
}

// QuotaUsdLT applies the LT predicate on the "quota_usd" field.
func QuotaUsdLT(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldQuotaUsd, v))
}

// QuotaUsdLTE applies the LTE predicate on the "quota_usd" field.
func QuotaUsdLTE(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldQuotaUsd, v))
}

// UsedUsdEQ applies the EQ predicate on the "used_usd" field.
func UsedUsdEQ(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedUsdNEQ applies the NEQ predicate on the "used_usd" field.
func UsedUsdNEQ(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldUsedUsd, v))
}

// UsedUsdIn applies the In predicate on the "used_usd" field.
func UsedUsdIn(vs ...float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldUsedUsd, vs...))
}

// UsedUsdNotIn applies the NotIn predicate on the "used_usd" field.
func UsedUsdNotIn(vs ...float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldUsedUsd, vs...))
}

// UsedUsdGT applies the GT predicate on the "used_usd" field.
func UsedUsdGT(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldUsedUsd, v))
}

// UsedUsdGTE applies the GTE predicate on the "used_usd" field.
func UsedUsdGTE(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldUsedUsd, v))
}

// UsedUsdLT applies the LT predicate on the "used_usd" field.
func UsedUsdLT(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldUsedUsd, v))
}

// UsedUsdLTE applies the LTE predicate on the "used_usd" field.
func UsedUsdLTE(v float64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldUsedUsd, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldContainsFold(FieldStatus, v))
}

// FrozenAtEQ applies the EQ predicate on the "frozen_at" field.
func FrozenAtEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldFrozenAt, v))
}

// FrozenAtNEQ applies the NEQ predicate on the "frozen_at" field.
func FrozenAtNEQ(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldFrozenAt, v))
}

// FrozenAtIn applies the In predicate on the "frozen_at" field.
func FrozenAtIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldFrozenAt, vs...))
}

// FrozenAtNotIn applies the NotIn predicate on the "frozen_at" field.
func FrozenAtNotIn(vs ...time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldFrozenAt, vs...))
}

// FrozenAtGT applies the GT predicate on the "frozen_at" field.
func FrozenAtGT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldFrozenAt, v))
}

// FrozenAtGTE applies the GTE predicate on the "frozen_at" field.
func FrozenAtGTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldFrozenAt, v))
}

// FrozenAtLT applies the LT predicate on the "frozen_at" field.
func FrozenAtLT(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldFrozenAt, v))
}

// FrozenAtLTE applies the LTE predicate on the "frozen_at" field.
func FrozenAtLTE(v time.Time) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldFrozenAt, v))
}

// FrozenAtIsNil applies the IsNil predicate on the "frozen_at" field.
func FrozenAtIsNil() predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIsNull(FieldFrozenAt))
}

// FrozenAtNotNil applies the NotNil predicate on the "frozen_at" field.
func FrozenAtNotNil() predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotNull(FieldFrozenAt))
}

// FrozenSecondsTotalEQ applies the EQ predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldEQ(FieldFrozenSecondsTotal, v))
}

// FrozenSecondsTotalNEQ applies the NEQ predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalNEQ(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNEQ(FieldFrozenSecondsTotal, v))
}

// FrozenSecondsTotalIn applies the In predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldIn(FieldFrozenSecondsTotal, vs...))
}

// FrozenSecondsTotalNotIn applies the NotIn predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalNotIn(vs ...int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldNotIn(FieldFrozenSecondsTotal, vs...))
}

// FrozenSecondsTotalGT applies the GT predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalGT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGT(FieldFrozenSecondsTotal, v))
}

// FrozenSecondsTotalGTE applies the GTE predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalGTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldGTE(FieldFrozenSecondsTotal, v))
}

// FrozenSecondsTotalLT applies the LT predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalLT(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLT(FieldFrozenSecondsTotal, v))
}

// FrozenSecondsTotalLTE applies the LTE predicate on the "frozen_seconds_total" field.
func FrozenSecondsTotalLTE(v int64) predicate.UserPackage {
	return predicate.UserPackage(sql.FieldLTE(FieldFrozenSecondsTotal, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserPackage) predicate.UserPackage {
	return predicate.UserPackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserPackage) predicate.UserPackage {
	return predicate.UserPackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserPackage) predicate.UserPackage {
	return predicate.UserPackage(sql.NotPredicates(p))
}
